hmcts/cmc-citizen-frontend

- Jenkinsfile
Reverts hmcts/cmc-citizen-frontend#19
Pen test has finished
> Revert "Disabled auto demo deploy to allow for T2 Pen testing"

- src/main/features/ccj/views/their-details.njk
fixed bug - defendant  email on CCJ "their details" confirmation page is displayed
> BUG: Display an email on 'their details' confirmation page for CCJ

- src/main/features/ccj/routes/check-and-send.ts
- src/main/features/ccj/views/check-and-send.njk
- src/main/features/ccj/views/their-details.njk
- src/main/features/claim/views/check-and-send.njk
- src/main/features/claim/views/claimant-company-details.njk
- src/main/features/claim/views/claimant-individual-details.njk
- src/main/features/claim/views/claimant-organisation-details.njk
- src/main/features/claim/views/claimant-sole-trader-details.njk
- src/main/features/claim/views/defendant-company-details.njk
- src/main/features/claim/views/defendant-individual-details.njk
- src/main/features/claim/views/defendant-organisation-details.njk
- src/main/features/claim/views/defendant-sole-trader-details.njk
- src/main/features/response/views/check-and-send.njk
- src/main/features/response/views/your-details.njk
- src/main/views/includes/macros/form.njk
- src/main/views/includes/macros/partyDetails.njk
- src/main/views/includes/macros/table.njk
https://tools.hmcts.net/jira/browse/ROC-2044
Adds more party details to the 'their details page' depending on party type + displays party details on the check & send page.
```
[ ] Yes
[n] No
```
> Apply party type to their-details and check-and-send CCJ pages

- src/main/app/forms/models/dateOfBirth.ts
- src/main/features/ccj/views/date-of-birth.njk
- src/main/features/claim/views/claimant-dob.njk
- src/main/features/response/views/your-dob.njk
- src/test/app/forms/models/dateOfBirth.ts
https://tools.hmcts.net/jira/browse/ROC-2341
Implementation is based on what I discussed with @BenClancy. If no need to internationalise the application that would be reasonable good solution however with a need for Welsh translation it requires to import `i18next` framework in both `src/main` and `src/test` code.
Also I am not sure the hint is in the right place. There are visually other ways of convey that hint. Would be good to check with @tarik-johnston1 on Monday.
```
[ ] Yes
[x] No
```
> Make 'must be over 18' validation error message generic

- Jenkinsfile
- yarn.lock
There's currently a nsp issue:
https://nodesecurity.io/advisories/525
With no fix, rather than suppressing it 
and forgetting about it we would prefer to keep getting notifications about it.
> Make NSP failure a warning

- config/dockertests.json
- src/main/routes/health.ts
- src/main/server.ts
Enable local ssl certs to setup https for 'dockertests' environment
```
[ ] Yes
[x] No
```
> Use local ssl certs to setup https for dockertests environment

- package.json
- yarn.lock
js-base64 was a transitive dependency of a devDependency
Which don't get bundled into what gets deployed.
```
$ yarn why js-base64
yarn why v1.1.0
[1/4] 🤔  Why do we have the module "js-base64"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info This module exists because "gulp-sass#node-sass#sass-graph#scss-tokenizer" depends on it.
info Disk size without dependencies: "68kB"
info Disk size with unique dependencies: "68kB"
info Disk size with transitive dependencies: "68kB"
info Number of shared dependencies: 0
``
> Add js-base64 to regular dependencies

- src/main/app/claims/claimModelConverter.ts
- src/main/app/utils/stringUtils.ts
- src/test/app/utils/stringUtils.ts
None
This is to deserialise optional defendant email address to udnefined if value is not provided e.g. is blank. Followup PR will be raised for the backend to migrate existing cases.
```
[ ] Yes
[x] No
```
> Deserialise optional defendant email address to udnefined if not provided

- src/test/features/ccj/form/models/repaymentPlan.ts
None
Test used to fail on Sundays because used `moment.day()` method does not return the day of month as everyone would expect but in fact it returns day of week. That caused 'Enter a valid day' validation error being triggered instead of expected 'Enter a first payment date in the future'.
```
[ ] Yes
[x] No
```
> Fix flaky unit test

- src/main/app/claims/responseModelConverter.ts
`OWE_ALL_PAID_ALL` response type has been split into response subtypes. But Claim Store still relies on it to compose a staff notification. This change is to provide a workaround that will fix the broken functionality. Frontend and backend models will be aligned properly as a part of finishing partial admission stories.
```
[ ] Yes
[X] No
```
> Workaround for unaligned response type models

- src/main/app/logging/errorLogger.ts
This aligns the citizen frontend with the claim store in how 404s are
logged.
It will also remove the spam in the production logs from webcheck scanning the
system for vulnerabilities
> Log 404 at debug

- src/main/features/response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-2162
Fix check and send page. Do not display "undefined", but ''.
```
[ ] Yes
[x] No
```
> ROC-2162: added filter default('') in check and send page for evidence description

- src/test/common/security/serviceTokenFactory.ts
- src/test/requireUtils.ts
None
That should fix master build. I have no good idea why it worked before and stopped working. Maybe node started handling this differently.
```
[ ] Yes
[x] No
```
> Fix removing 'serviceTokenFactoryImpl' from node cache in unit tests

- gulpfile.js
- src/main/modules/nunjucks/index.ts
None
Nunjucks engine has a watch feature which reloads template file without a need to restart whole node process. That should speed up development process by reducing wait time when only template changes are being made.
```
[ ] Yes
[x] No
```
> Stop restarting node process on template change

- .nsprc
- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/ROC-2864
Running `yarn setup` after the build stage as it's not a part of the CNP default pipeline. Also added an NSP exception for https://nodesecurity.io/advisories/532
> Run yarn setup in CNP, add an NSP exception

- Jenkinsfile
- package.json
https://tools.hmcts.net/jira/browse/ROC-2864
CNP pipeline expects a `sonar-scan` yarn task to be available, we named ours `sonar-scanner`.
> ROC-2864: Align sonar scan task to CNP requirements

- src/main/public/js/evidence-select-handler.js
Fixed broken JS script. `timeline` class was replaced with `multiline` as it's more generic name.
> ROC-2772: fixed js for evidence page

- package.json
- yarn.lock
Reverts hmcts/cmc-citizen-frontend#256 due to the problem with:
```
2017-12-11T11:22:06+00:00 INFO testing-support: Testing support activated
2017-12-11T11:22:07+00:00 INFO applicationRunner: Port value was not set using PORT env variable, using the default of 3000
Error: listen EADDRINUSE :::3000
```
> Revert "Update ts-node to the latest version 🚀"

- .dockerignore
- .travis.yml
- Dockerfile
- Jenkinsfile
- gulpfile.js
- package.json
- tsconfig.prod.json
https://tools.hmcts.net/jira/browse/ROC-2908
This PR removes TS to JS compilation and brings back ts-node for running services.
> ROC-2908: Remove TS to JS compilation and start service using ts-node

- package.json
- src/test/app/logging/requestTracingHandler.ts
https://tools.hmcts.net/jira/browse/ROC-2908
This PR brings back type checking. Type checking is done before listing starts. That brings the behaviour removed by us when `tslint` deprecated `--type-check` CLI flag.
Type checking when `yarn lint` is executed will give us type safety before committing code and on Jenkins. In remaining cases IDE will highlight compilation errors in opened files we actively work on.
> ROC-2908: Include type checking in linting step

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/ROC-1105
Use latest version of nodejs-logging to add tracing headers on all logging calls.
> ROC-1105: Use latest nodejs-logging 

- src/main/features/claim/routes/receipt.ts
- src/main/features/response/routes/receipt.ts
Previous implementation ignored a status message possibly returned in the error response.
> Improve receipt download logging

- src/main/app/forms/utils/multiRowFormUtils.ts
- src/main/features/response/routes/statement-of-means/court-orders.ts
- src/main/features/response/routes/statement-of-means/debts.ts
- src/main/features/response/views/statement-of-means/check-and-send.njk
- src/test/app/forms/utils/multiRowFormUtils.ts
https://tools.hmcts.net/jira/browse/ROC-2772
Fix number of rows displayed by default (other court orders)
Fix bottom border on check and send page
> ROC-2772: fix issue with number of rows displayed on other court orders

- src/main/app/claims/ccjClient.ts
- src/main/features/ccj/routes/check-and-send.ts
- src/test/features/ccj/routes/check-and-send.ts
- src/test/http-mocks/claim-store.ts
[ROC-3017](https://tools.hmcts.net/jira/browse/ROC-3027)
This PR accommodates the changes in `cmc-claim-store`, which uses the external id to save CCJ rather than claim database id.
Relevant pull request at `cmc-claim-store` repo is: https://github.com/hmcts/cmc-claim-store/pull/161
> ROC-3027: Use external id as identifier rather than database id

- src/main/routes/receiver.ts
Unlikely to happen to a real user but the claim store was giving errors
for me on login and the page hung.
This was because the `then` and `catch` blocks were both making calls to
the claim store, I've added another catch block which just uses our
error handler
> Fix hang on login failure

- gulpfile.js
- package.json
- src/main/routes/postcode-lookup.ts
- src/main/views/postcode-lookup-client-scripts.njk
- yarn.lock
https://tools.hmcts.net/jira/browse/ROC-3135
- provided a polyfill for missing `startsWith` `String` function on IE
- changed the postcode lookup endpoint to return 400 status when client does not send a postcode
> ROC-3135: Provide startsWith polyfill and return 400 error on validation failure

- src/test/features/response/draft/payBySetDate.ts
- src/test/features/response/tasks/whenWillYouPayTask.ts
February has 28 days, 1 month is currently equalling 28 days whereas the
check is for greater than 28 days, so do 29 days -.-
> Fix date tests

- src/main/public/js/analytics-custom-event-sender.js
Because of the `for...of` loop, IE didn't work.
Reworked the code so the loop isn't needed
It assumes the text will always be the first element, have tested on
eligibility
> ROC-3132 Fix custom event sender in IE

- package.json
- src/main/public/stylesheets/components/_task-list.scss
- yarn.lock
Screen readers aren't reading out the sections when headers are being
read out which means the context isn't is good as it could be.
> Use heading for task-list rather than bold span

- .nsprc
Build is failing on CNP environment on NSP check stage.To suppress error  Ignore hoek from nsp check.
- [x ] No
> Ignore hook error from nsp check

- src/main/features/response/views/macro/expandableSection.njk
- src/main/public/stylesheets/components/_expandable-content.scss
https://tools.hmcts.net/jira/browse/ROC-3113
Problem was reported when text had break lines. In that case rendered text had greater height then fixed 125px set for content container.
The solution is to make content container adjust to the content hight if limit of characters (default 400) is not exceeded. In opposite scenario where limit is exceeded fixed height is applied and more / less links are rendered.
> ROC-3113: Fix expandable section so that it handles content with break lines

- src/main/features/first-contact/routes/claim-summary.ts
- src/main/features/first-contact/views/claim-summary.njk
- src/main/features/response/routes/claim-details.ts
- src/main/features/response/views/claim-details.njk
- src/main/views/macro/amountBreakdown.njk
None
This PR uses dates range from `InterestData` when amount break down is displayed. This is to correctly handle the scenario when issue date is next day due to the fact claim was issued after 4pm.
Screenshot:
> Fix: Use correct interest dates range in interest breakdown

- src/main/app.ts
Application insights provides the same and doubling up makes insights
really hard to use
> ROC-3224 Remove express access logger

- src/main/app/utils/callbackBuilder.ts
- src/test/app/utils/callbackBuilder.ts
- src/test/features/first-contact/routes/claim-reference.ts
- src/test/features/first-contact/routes/claim-summary.ts
- src/test/routes/authorization-check.ts
The setting that was used in CNP to force redirect http to https appears
to get overridden by deployments, we will look to get this fixed
properly but this change should stop users from not being able to
complete their journeys
> Always redirect to SSL

- src/integration-test/tests/citizen/defence/pages/defendant-register.ts
They changed the text on the register page which broke the pin and post login in our integration tests:
container update: https://github.com/hmcts/cmc-integration-tests/pull/167
I ran the test against AAT after updating the test and:
```
OK  | 1 passed   // 51s
```
> Update to new idam version

- config/default.json
- src/main/views/cookies.njk
2 days is the length of time idam activation emails are valid for, Martin requested this config value to be updated
> ROC-3215 Update eligibility cookie ttl to 2 days

- src/main/features/eligibility/model/eligibility.ts
- src/test/features/eligibility/model/eligibility.ts
Improved logic for defendantAge question to allow Organisation to be selected and classified as eligible to prevent a looping back to the start of eligibility questions, on submission.
> Bug Fix: Allow Yes and Organisation option for defendantAge, to create a valid claim

- src/main/features/ccj/views/paid-amount-summary.njk
- src/main/views/macro/amountBreakdown.njk
- src/main/views/macro/interestSnippet.njk
[ROC-3482](https://tools.hmcts.net/jira/browse/ROC-3482)
When claimant has selected no daily interest, we are still displaying the daily interest details with £0 for N days etc. This should not be displayed in this case. Also updated the label from `Interest to date` to `Interest` as advised.
> ROC-3482: For no daily interest selected, details of daily interest should not be listed

- package.json
- yarn.lock
[ROC-3501](https://tools.hmcts.net/jira/browse/ROC-3501)
This PR upgrades `requestretry` version to `1.1.2`, which fixes the issue raised in [ROC-3501](https://tools.hmcts.net/jira/browse/ROC-3501)
> ROC-3501: Upgrade requestretry version

- src/test/app/claims/claimModelConverter.ts
https://tools.hmcts.net/jira/browse/ROC-3435
This PR changes claim converter test to assert JSON in the format that is being sent to the API instead of comparing JSON literals with Moment instances that are terrible to call `equals` against.
> ROC-3435: Make claim converter test compare JSON objects instead of JSON literals

- package.json
- src/test/app/common/calculateInterest.ts
- src/test/common/interestUtils.ts
- src/test/features/claim/guards/claimEligibilityGuard.ts
- src/test/features/response/routes/how-much-owed.ts
- src/test/features/response/routes/how-much-paid.ts
- src/test/features/response/routes/when-did-you-pay.ts
- src/test/hooks.ts
- src/test/http-mocks/claim-store.ts
- src/test/routes/hooks.ts
None
There were two causes:
- some unit tests that utilised nock mocks did not verify / clear unused mocks which meant that these mocks remained and were used in other tests. That caused tests from file A impact tests from file B.
- calculate interest nock mock was set in invalid way so in conjunction with previous issue it caused that 'get claim by external ID' used to received response from 'calculate interest' mock
Solution:
- I verified, removed unused mocks and added hooks to detect it in the future
- I fixed mock for calculate interest endpoint
- I rewritten calculate interest tests to make these useful / readable
> Fix 3 tests failures on CNP Jenkins

- package.json
```
D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:193
orig.apply(this, arguments);
^
Error: Cannot find module 'lodash'
at new AppInsightsAsyncCorrelatedErrorWrapper (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:193:18)
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._resolveFilename (D:\home\site\wwwroot\node_modules\tsconfig-paths\lib\register.js:31:40)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at Module.patchedRequire [as require] (D:\home\site\wwwroot\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
at require (internal/module.js:11:18)
at Object.<anonymous> …
```
> Try fix broken cnp deployment

- src/main/features/claim/views/interest-rate.njk
- src/main/features/claim/views/interest.njk
- src/main/features/eligibility/views/claimant-address.njk
- src/main/features/eligibility/views/defendant-address.njk
- src/test/features/eligibility/routes/claimant-address.ts
- src/test/features/eligibility/routes/defendant-address.ts
1. I've changed the two eligibility questions which mention an address so they say "postal address" instead - this is apparently important.
2. I've added "this is the statutory rate" to the help text when we talk about 8% interest - on two different pages. This is apparently important and insisted on despite the lack of a user need.
> Content changes based on Civil Procedure rules feedback

- src/main/modules/app-insights/index.ts
https://tools.hmcts.net/jira/browse/ROC-3462
Obfuscating UUID's in urls to {uuid} before being sent to App Insights
> Application Insights: obfuscate UUID's in url's which are not static files

- src/main/features/response/views/response-type.njk
Fire an event to Google Analytics when a user clicks on the details section on the response-type page. This will let us track if users are looking at the information before choosing an option.
> Add GA event for response type details

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- infrastructure/main.tf
- infrastructure/output.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/ROC-3940
Use azure key vault for secrets instead of hashi vault
> ROC-3940 Use key vault no more hashi vault

- src/main/features/response/routes/full-admission/payment-option.ts
- src/main/features/response/views/statement-of-means/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-3658
This PR fixes two flaws found in testing:
1. Payment option hints were not displayed for pay by set date and pay by instalments radio options. The reason was that used `isApplicableFor` function expected option to be selected which it was impossible on the screen that helps user make decision around payment option.
2. Horizontal line was not present on check and send page when defendant was self employed but not behind on tax payments.
> ROC-3658: Fix full admission payment option hints and line resending on check and send page

- src/main/app/common/paymentPlan.ts
- src/test/features/response/routes/full-admission/payment-plan.ts
There is already a route test for the payment-plan page for when `response:full-admission` is used
This test isn't the right place to be testing the logic of the calculation so there is no value in keeping it there
> Fix rounding error to calculate number of instalments

- src/main/features/response/routes/full-admission/payment-plan.ts
On the payment plan page, we previously displayed the initial claim amount
eg. £3141.59.
The content specified this number was meant to include the claim, claim fees and interest.
This change aligns up with what is expressed in the content
> Changed value displayed from claim amount to claim + fees

- src/main/features/response/views/macro/statement-of-means/incomeExpenseSource.njk
Inline pound input macro duplicates the label on mobile, because its only used in multi row forms apart from here...
> ROC-3859 Remove mobile label duplicate

- src/main/features/claimant-response/paths.ts
- src/test/a11y/a11y.ts
- src/test/http-mocks/draft-store.ts
https://tools.hmcts.net/jira/browse/ROC-4052
This PR adds `a11y` tests for claimant-response feature.
> ROC-4052: Add `a11y` tests for claimant response feature

- src/main/app/claims/models/response/core/paymentIntention.ts
- src/main/app/claims/models/response/fullAdmissionResponse.ts
- src/main/app/claims/models/response/partialAdmissionResponse.ts
- src/main/app/claims/responseModelConverter.ts
- src/main/features/claimant-response/helpers/taskListBuilder.ts
- src/main/features/response/views/confirmation/full-admission-steps.njk
- src/main/features/response/views/confirmation/full-admission.njk
- src/test/data/entity/responseData.ts
None
This PR makes full admission catchup in terms of how payment intention is represented in domain model.
> Use payment intention object in full admission response

- src/main/app/claims/models/response/partialAdmissionResponse.ts
- src/main/app/claims/responseModelConverter.ts
- src/main/features/response/views/confirmation/part-admission-steps.njk
- src/main/features/response/views/confirmation/part-admission.njk
- src/test/data/entity/responseData.ts
None
Removes 'isAlreadyPaid' property from partial admission response that should have been removed when structure changed.
> Remove unneeded property from partial admission response

- src/main/features/response/views/confirmation.njk
- src/main/features/response/views/confirmation/full-defence-steps.njk
- src/main/features/response/views/confirmation/full-defence.njk
1. Changed 'your claim reference to claim number'
2. Removed the 'your response' heading from below the green box
3. Changed 'defence' to 'response' in the line underneat the green box.
4. Deleted the line that appears linking them to the dashboard which read 'view the claim against you and your response' - we already link to the dashboard further down the page.
5. Made the info about the case being reviewed and the hearing less passive, the court will review the case and you might have to go to a hearing.
6. Changed 'may' to 'can' in the settle section.
7. Changed 'fix' to 'repair'
> Defendant confirmation page changes

- package.json
- src/integration-test/tests/citizen/ccj/ccj_test.ts
- src/integration-test/tests/citizen/claim/enterDetails_test.ts
- src/integration-test/tests/citizen/claim/fees_test.ts
- src/integration-test/tests/citizen/claim/pages/claimant-claim-confirmed.ts
- src/integration-test/tests/citizen/claim/payment_test.ts
- src/integration-test/tests/citizen/claim/steps/claim.ts
- src/integration-test/tests/citizen/dashboard/dashboard_test.ts
- src/integration-test/tests/citizen/defence/defence_claim_details_test.ts
- src/integration-test/tests/citizen/defence/defence_handoff_test.ts
- src/integration-test/tests/citizen/defence/defence_test.ts
- src/integration-test/tests/citizen/defence/full_admission_test.ts
- src/integration-test/tests/citizen/defence/part_admission_test.ts
- src/integration-test/tests/citizen/endToEnd/endToend_test.ts
- src/integration-test/tests/citizen/govukAccessRoutes/respondToClaim_test.ts
- src/integration-test/tests/citizen/govukAccessRoutes/returnToClaim_test.ts
- src/integration-test/tests/citizen/offers/offers_test.ts
- src/integration-test/tests/citizen/testingSupport/testingSupport_test.ts
- tsconfig.json
- types/steps-override.d.ts
- yarn.lock
None
The main change is to replace scenario hooks with regular method calls as failures in hooks are not eligible for retries. Unfortunately to enable these method calls I needed to use async / await approach, otherwise I was getting wired results.
> Remove scenario hooks and replace generators with async/await

- src/main/features/response/views/check-and-send.njk
None
The fix displays payemnt details only when amount has bot been paid.
In remaining cases just timeline and evindence is displayed.
> [PREVIEW] Fix check-and-send page for partial admission

- src/main/features/testing-support/views/delete-drafts.njk
Allows to delete claimant response drafts from the UI, missed during project setup
> Add claimant response draft deletion

- src/main/features/claimant-response/helpers/settlementHelper.ts
- src/test/features/claimant-response/helpers/settlementHelper.ts
This PR adds missing `paymentIntention` in defendant offer for settlement through admissions.
> Add missing payment intention for defendant offer

- src/main/app/common/payment-plan/paymentPlan.ts
- src/main/public/js/payment-plan-calculation.js
- src/test/app/common/payment-plan/paymentPlan.ts
https://tools.hmcts.net/jira/browse/ROC-4295
when user was selecting 'monthly' option in repayment plan, the endpoint was receiving the wrong frequency in weeks. It was getting '4' weeks in a month instead of '4.33' (52 weeks / 12 months)
> ROC-4295 change of payment-plan length calculation logic

- src/main/app/claims/converters/claimantResponseConverter.ts
- src/main/features/claimant-response/routes/payment-date.ts
- src/test/app/claims/converters/claimantResponseConverter.ts
ROC-4593
Remove error thrown when repayment plan decision is for the claimant (in favour of the defendant) and no court plan is generated
> ROC-4593 Allow missing court's plan when decision is CLAIMANT_IN_FAVOUR_OF_DEFENDANT

- src/main/public/js/income-expense-calculation.js
- src/main/views/income-expense-scripts.njk
https://tools.hmcts.net/jira/browse/ROC-4639
Fixing income expense calculation formatting to 2 decimal places - as per prototype. Used in monthly income, priority debts and monthly expenses screens.
- [ X ] I have clicked through the running application to see if all changes I made actually work.
- [ X ] No
> ROC-4639: use correct decimal places for income expense calculation

- src/main/features/claimant-response/views/confirmation.njk
- src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
- src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
https://tools.hmcts.net/jira/browse/ROC-4805
Use the DB-stored directions questionnaire deadline rather than calculating it on the front-end or using the response deadline
> ROC-4805 Directions questionnaire deadline after reject part admit

- src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
https://tools.hmcts.net/jira/browse/ROC-4903
The stored `claimantResponse` was being inspected as though it were a draft; treating it as a boolean makes nunjucks evaluate it correctly
> ROC-4903 Fix reject part admit with mediation

- src/main/features/dashboard/views/macro/claimStatus/paidInFullDefendant.njk
https://tools.hmcts.net/jira/browse/ROC-4336
Added in extra info to the paid in full defendant dashboard status, when the claim is settled by a CCJ paid within or over a month. A link to get a certificate of satisfaction for a CCJ was added.
> If you need proof that the CCJ is paid you can contact us to get a certificate of satisfaction. This costs £15.
> ROC-4301: Paid in full for admissions, adding CCJ certificate link

- infrastructure/main.tf
Adding a dummy setting to force terraform update with admissions turned on. 
- [ X ] No
> turn on admissions in aat (fix)

- src/main/routes/health.ts
https://tools.hmcts.net/jira/browse/ROC-5111
SPROD deployment is failing because no Pay deployment is present. SPROD uses mockPay so check is irrelevant. This change will disable healthcheck when frontend configured to use mockPay.
Tested locally with mockPay on and off (switching docker pay service on and off too).
- [ x ] No
> ROC-5111: disable healthcheck on pay service when using mockPay=true

- docker-compose.yml
Fix local docker-compose image to match image in cmc-integration-tests.
> Fix image to match integration tests

- Dockerfile
Allow the `hmcts` user to perform changes on the application source folder.
Here is the [related documentation](https://github.com/hmcts/cnp-node-base#yarn-install-fails-because-of-permission-issues)
-> The health check does respond.
> Fix user permission on docker build step

- .dockerignore
Avoid the acb.yaml file and the Dockerfile (!) to be in the ignore list of docker build. The ACR bundling takes the .dockerignore files in account and doesn't upload the acb.yaml or the Dockerfile with the existing rules, hence the build failure.
> Exclude the acb.yaml file from being ignored on acr build

- Jenkinsfile_nightly
Nightly functional tests throw: `401 - {"error":"redirect_uri is not white listed","code":"INCORRECT_CREDENTIALS"}` ... the redirect_uri needs to be exact and comparing to TEST_URL in normal pipeline - only diff is trailing slash.
> Remove trailing slash from nightly test_url

- infrastructure/output.tf
https://build.platform.hmcts.net/job/HMCTS_CMC/job/cmc-citizen-frontend/job/master/326/console
This new code in Jeninsfile:
```
def secrets = [
'cmc-${env}':
[
secret('citizen-oauth-client-secret', 'OAUTH_CLIENT_SECRET'),
secret('smoke-test-citizen-username', 'SMOKE_TEST_CITIZEN_USERNAME'),
secret('smoke-test-user-password', 'SMOKE_TEST_USER_PASSWORD')
],
'rpe-ft-api-${env}' :
[
secret('admin-username-test', 'ADMIN_USERNAME_TEST'),
secret('admin-password-test', 'ADMIN_PASSWORD_TEST'),
secret('editor-username-test', 'EDITOR_USERNAME_TEST'),
secret('editor-password-test', 'EDITOR_PASSWORD_TEST')
]
]
```
This error:
```
org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultException: Secret: admin-username-test not found in vault: https://cmc-aat.vault.azure.net/
at …
```
> Fix AAT build on master

- src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
- src/test/data/entity/responseData.ts
- src/test/features/dashboard/routes/index.ts
- src/test/http-mocks/claim-store.ts
https://tools.hmcts.net/jira/browse/ROC-5265
- Adding a first battery of route tests covering a few cases in admissions. This will help to set up a pattern to follow for adding subsequent route tests.
- Also, fixing a UI bug surfaced by the route tests themselves. We were missing a `| numeral` filter in a template, so we were rendering a money amount as a simple integer
> ROC-5625 Add route tests for claim issued and admissions, and fix UI bug

- package.json
- src/main/features/dashboard/helpers/claimStatusFlow.ts
- src/main/features/dashboard/index.ts
- src/main/features/dashboard/views/index.njk
- src/main/features/dashboard/views/status/claimant/claim_issued.njk
- src/main/features/dashboard/views/status/defendant/claim_issued.njk
- src/test/features/dashboard/helpers/claimStatusFlow.ts
- tslint.json
- yarn.lock
https://tools.hmcts.net/jira/browse/ROC-5258
- Introducing a new way of discerning the dashboard status from a claim. It will still be picked based on the state of a claim (as it is now), but will be calculated using a 'flowchart'-like data structure instead of complex if-elses. This should make everything more testable and also it should be easier to follow what's going on.
- Added some additional guards to make sure we default to the old way if the new rule engine can't find a dashboard status / the rule engine itself is wrong. Those will be removed once we have migrated all the statuses and we are confident the rule engine works.
- Added a tslint rule to stop committing `.only` in tests (guilty!)
In more detail: 
- Each element of this flowchart has a `description` (for documentation …
> ROC-5258 Refactor claim issue dashboard

- package.json
https://build.platform.hmcts.net/job/HMCTS_Nightly_CMC/job/cmc-citizen-frontend/job/master/
```
09:19:35 [_CMC_cmc-citizen-frontend_master] Running shell script
09:19:35 + yarn test:crossbrowser
09:19:35 yarn run v1.12.3
09:19:35 error Command "test:crossbrowser" not found.
09:19:35 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
> Fix nightly cross-browser test

- src/main/features/dashboard/index.ts
- src/main/features/dashboard/views/index.njk
- src/test/features/dashboard/routes/index.ts
https://tools.hmcts.net/jira/browse/ROC-5265
This disables the rendering of new dashboard statuses - we need to get a vertical slice of a flow to the very end to avoid messing up with the logic. 
Ie. a settled claim is incorrectly considered issued because the entirety of the journey is not yet modelled. This is currently being addressed in https://github.com/hmcts/cmc-citizen-frontend/pull/1502 where we take full admission all the way through
> ROC-5265 Disable rendering of new dashboard statuses

- src/test/features/claim/routes/claimant-dob.ts
no ticket
A bit of an 'ooof' moment. Using month() makes the `LocalDate` for that test be ```LocalDate { year: 2018, month: 2, day: 29 }``` which is not a valid date, so the validation is different than expected. 
This breaks the pipeline on the 29th of March of all non leap years _<nerdface.jpg>_ 💃
> Bug - Fix route test date mishap and unblock pipeline

- src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
Change check for I.dontSeeText('COMPLETE') in e2e tests for a CSS selector that selects the COMPLETE task
> Fix e2e picking up 'INCOMPLETE' task as 'COMPLETE'

- Jenkinsfile_nightly
Revert any changes to location of these env vars - back to where they were when e2e were running successfully. Scope must matter!
> Move nightly env vars to correct scope

- charts/cmc-citizen-frontend/values.preview.template.yaml
AKS Preview environments always going to handoff page for admissions. The feature toggle api url is wrong!!!
> Fix feature-toggle api url

- src/main/features/dashboard/views/macro/claimStatus/offerAccepted.njk
- src/test/features/dashboard/routes/claimStatus/full-defence.ts
https://tools.hmcts.net/jira/browse/ROC-5873
Remove option to start the CCJ journey from the claim status page when accepted defendant's offer and pending countersignature.
> ROC-5873 Remove link to CCJ on claimant's offer accepted claim status page

- charts/cmc-citizen-frontend/Chart.yaml
- charts/cmc-citizen-frontend/requirements.yaml
Bump feature toggles api version which uses "hmctspublic"
- [ x] No
> bump version to fetch feature-toggle api from hmctspublic

- src/main/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
- src/test/features/claimant-response/helpers/taskListBuilder.ts
- src/test/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
https://tools.hmcts.net/jira/browse/ROC-6200
Clicking submit on claimant response was causing a court name null pointer exception
> ROC 6200 check and send court name must not be null

- src/main/public/js/date-picker.js
https://tools.hmcts.net/jira/browse/ROC-6413
Candidate fix for the missing date-picker on IE11 and Edge browsers. The error indicated a javascript parsing issue with a trailing comma that most browsers ignore but IE11 & Edge complain about.
> ROC-6413 Tidy date-picker integration code, for IE11 and Edge compatibility

- src/main/public/js/date-picker.js
https://tools.hmcts.net/jira/browse/ROC-6413
Continuation of https://github.com/hmcts/cmc-citizen-frontend/pull/1849
Found comments that Edge also doesn't like the `...spread` notation.
> ROC-6413 date-picker compatibility with IE11 and Edge

- src/main/public/js/date-picker.js
Following ECMAScript 6 features have been converted to ES5 equivalent:
* Arrow Functions: http://es6-features.org/#ExpressionBodies
* Enhanced Object Properties: http://es6-features.org/#PropertyShorthand
> Removed ECMAScript syntactic sugar not supported in IE11

- src/main/features/dashboard/views/macro/caseStatus.njk
- src/main/features/dashboard/views/macro/claimStatus/admissionByCCJClaimant.njk
- src/main/features/dashboard/views/macro/claimStatus/admissionByCCJDefendant.njk
- src/main/features/dashboard/views/macro/claimStatus/breachOfPaymentDefendant.njk
- src/main/features/dashboard/views/macro/claimStatus/ccjEligible.njk
- src/main/features/dashboard/views/macro/claimStatus/ccjRequested.njk
- src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForClaimant.njk
- src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForDefendant.njk
- src/main/features/dashboard/views/macro/claimStatus/claimPartAdmissionClaimant.njk
- src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
- src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
- src/main/features/dashboard/views/macro/claimStatus/claimantResponse.njk
- src/main/features/dashboard/views/macro/claimStatus/moreTimeRequested.njk
- src/main/features/dashboard/views/macro/claimStatus/noReponse.njk
- src/main/features/dashboard/views/macro/claimStatus/offerAccepted.njk
- src/main/features/dashboard/views/macro/claimStatus/offerRejected.njk
- src/main/features/dashboard/views/macro/claimStatus/offerSettlement.njk
- src/main/features/dashboard/views/macro/claimStatus/offerSubmitted.njk
- src/main/features/dashboard/views/macro/claimStatus/orders.njk
- src/main/features/dashboard/views/macro/claimStatus/paidInFullClaimant.njk
- src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
- src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
- src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedClaimant.njk
- src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedDefendant.njk
- src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
- src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
- src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
- src/test/features/dashboard/routes/dashboard/full-defence.ts
https://tools.hmcts.net/jira/browse/ROC-6387
Update all H2 classes on claim status pages, that are directly after <div>, to the heading-medium class.
> ROC 6387 claim status page h2 incorrect size

- src/main/app/logging/customEventTracker.ts
- src/main/features/claim/routes/pay.ts
- src/test/features/claim/routes/pay.ts
- src/test/http-mocks/claim-store.ts
https://tools.hmcts.net/jira/browse/ROC-6701
Only delete the draft claim when claim is submitted successfully. This will allow any successful payment followed by unsuccessful claim submission to be resubmitted by the citizen user without additional payment.
> ROC-6701 Only delete the draft claim when claim is submitted successfully

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/ROC-6885
Bump the draft-middleware dependency which now returns the latest draft if there are multiple, instead of throwing an exception
> ROC-6885 Bump cmc-draft-store-middleware version to 2.0.1

- security.sh
Zap-cli scanning complaining about python2 and python3 compatibility.
This change will fix the issue.
- [x ] No
> fix Zap-cli complaining about python2 and python3 compatibility

- src/main/features/claim/helpers/featuresBuilder.ts
- src/main/features/claim/routes/finish-payment.ts
- src/main/features/claim/routes/pay.ts
- src/test/features/claim/helpers/featuresBuilder.ts
**NOTE:** To be merged in tandem with https://github.com/hmcts/cmc-claim-store/pull/1494
https://tools.hmcts.net/jira/browse/ROC-7619
Adjust features builder to accept an amount (which was all it needed anyway).
Adjust IoC submission journey to invoke the features builder with the retrieved claim from CCD instead of the draft.
> [To merge 19 March] ROC-7619 Decide features from the saved claim, in IoC

- src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
- src/test/features/dashboard/routes/claimStatus/full-defence.ts
https://tools.hmcts.net/jira/browse/ROC-7926
Add line to claimant and defendant dashboards when the claimant continues with the claim after defendant disputes all without mediation, and when mediation failed, to say that the claim will continue offline by post and the online service won't be updated.
> ROC-7926 No mediation and mediation failed dashboards to show updates will be by post

- src/main/app.ts
- src/main/app/utils/featureToggles.ts
- src/main/modules/nunjucks/index.ts
- src/test/app/utils/featureToggles.ts
https://tools.hmcts.net/jira/browse/ROC-8101
Move responsibility for providing the warning_banner toggle state to Node.js; nunjucks will then just consume it
> ROC-8101 Move injection of the warning_banner toggle state to Node.js, just consume in nunjucks

- src/main/features/dashboard/views/macro/claimStatus/claimTransferred.njk
https://tools.hmcts.net/jira/browse/ROC-8246
A fix to the live incident  where the claimant is not able to navigate to claim page and download the claim documents when. the case status is transferred.
> ROC-8246: Claimant cannot view transferred cases online

- src/main/app/claims/models/claim.ts
- src/main/features/response/routes/claim-details.ts
- src/main/features/response/views/claim-details.njk
- src/main/views/macro/interestCalculation.njk
> https://tools.hmcts.net/jira/browse/ROC-8638
> Displaying the breakdown of Interest calculations when the claimant has opted to claim interest at the same rate for the whole period.
**Background:**
When the claimant is claiming interest at a same rate for the whole period, Interest calculator automatically calculates the interest in the back-end and display it to the claimant directly in the Claim amount page of the user journey while submitting the case . We don't display to the Claimant on how that Interest got calculated which at times is misleading for the claimant. 
**Problem Statement:** 
Claimant is unaware on how the Interest component of the claim amount got calculated when they have opted to claim interest at the same rate for the whole period.
**Solution implemented:**   
1. …
> Displaying the breakdown of Interest calculations when the claimant has opted to claim interest at the same rate for the whole period.

- src/main/features/eligibility/views/help-with-fees-reference.njk
- src/main/features/eligibility/views/help-with-fees.njk
- src/test/features/eligibility/routes/help-with-fees.ts
https://tools.hmcts.net/jira/browse/ROC-8881
There were a HMCTS judge's review on the HwF UI screens. They were very happy with the overall screen content and the journey but advised some small content changes for the UI screens. This ticket will try to address those minor changes.
1. Please change the Title from ‘Do you need help paying your court fees?’ to ‘Do you need help paying your court fee?’  The judge / Kerry wanted to ensure that at this stage, it is clear that the HwF application only applies to the claim issue fee and as such Fees should be singular rather than plural.
2. Please add further wording to the sentence under the title.  This should now read ‘You’ll only have one if you’ve already applied for Help with Fees in respect of this claim.’ - The judge wanted to ensure …
> Content updates to HwF Citizen UI post review of HMCTS Judges

- src/main/common/helpers/ccjHelper.ts
- src/test/features/ccj/routes/repayment-plan-summary.ts
https://tools.hmcts.net/jira/browse/ROC-7513
In case of CCJ if paid amount is already updated we should not remove CCJ paid amount again  from the total amount.
1. If CCJ created from Part Admission pay by set date and claimant accepts the offer formalises CCJ --> Claim.paidAmount is updated with CCJ paid amount
2. If CCJ created from Part Admission pay immediately and claimant accepts the offer --> defendant does not pay within deadline --> claimant raises CCJ --> Claim.paidAmount is null and calculations are made from CCJ paidamount
> Partial paid amount is deducted twice and showing incorrect payment amount on Repayment plan screen

- src/main/views/cookies.njk
Home page: <title>Your money claims account - Money Claims</title>
Cookies page: <title> - Money Claims</title>
Untested but should be fine
> Fix title missing on cookies page
