src/main/common/router/routablePath.ts, src/main/features/ccj/routes/paid-amount-summary.ts, src/main/features/ccj/routes/paid-amount.ts, src/main/features/ccj/routes/payment-options.ts, src/main/features/claim/routes/pay.ts, src/main/features/dashboard/routes/claimant.ts, src/main/features/dashboard/routes/defendant.ts, src/main/features/first-contact/routes/claim-summary.ts, src/test/a11y/a11y.ts, src/test/common/router/routablePath.ts, src/test/features/ccj/routes/ccjGuard.ts, src/test/features/ccj/routes/paid-amount-summary.ts, src/test/features/ccj/routes/paid-amount.ts, src/test/features/ccj/routes/payment-options.ts, src/test/features/ccj/routes/their-details.ts, src/test/features/claim/routes/confirmation.ts, src/test/features/claim/routes/pay.ts, src/test/features/claim/routes/receipt.ts, src/test/features/claim/routes/response-copy.ts, src/test/features/dashboard/routes/claimant.ts, src/test/features/dashboard/routes/defendant.ts, src/test/features/response/routes/defendant-link-receiver.ts, src/test/features/response/routes/response-receipt.ts
No
A method to evaluate URI from the template with placeholders and an array of path parameters.
```
[ ] Yes
[x] No
```
=> Method to merge path URI with path parameters

src/main/features/ccj/views/date-of-birth.njk
https://tools.hmcts.net/jira/browse/ROC-1531
Fix select option link validation bug for CCJ defendant date of birth
```
[ ] Yes
[ x] No
```
=> ROC-1531 - Fix select an option link bug

src/main/app/utils/momentFormatter.ts, src/main/resources/pdf/issueReceipt.njk, src/main/resources/pdf/responseReceipt.njk, src/test/app/pdf/mappers/defendantMapper.ts, src/test/app/utils/momentFormatter.ts, src/test/modules/nunjacks/filters/dateFilter.ts
https://tools.hmcts.net/jira/browse/ROC-2299
Change the way date is displayed:
- in one line
- full month name
```
[ ] Yes
[x] No
```
=> ROC-2299 Submitted date on pdf

src/main/features/claim/views/interest-date.njk, src/main/features/claim/views/interest.njk
https://tools.hmcts.net/jira/browse/ROC-2291
Added help text in drop down 'help with interest rate'
```
[ ] Yes
[X ] No
```
=> ROC-2291 Feature/roc 2291 bug fix

src/main/routes/receiver.ts, src/test/routes/receiver.ts
https://tools.hmcts.net/jira/browse/ROC-2317
```
[ ] Yes
[X] No
```
=> ROC-2317 Fix login logic for defendant

package.json
None
Version bump for future development
```
[ ] Yes
[x] No
```
=> Bump version for future development

src/main/app/common/partyType.ts, src/main/app/drafts/models/defendant.ts, src/main/features/ccj/draft/DraftCCJ.ts, src/main/features/ccj/guards/individualDateOfBirthGuard.ts, src/main/features/ccj/routes/date-of-birth.ts, src/main/features/ccj/routes/their-details.ts, src/main/views/includes/macros/partyDetails.njk, src/test/a11y/mocks.ts, src/test/data/draft/partyDetails.ts, src/test/features/ccj/guards/individualDateOfBirthGuard.ts, src/test/features/ccj/routes/date-of-birth.ts, src/test/features/ccj/routes/their-details.ts
https://tools.hmcts.net/jira/browse/ROC-1531
This is to hide defendant date of birth page when CCJ is requested for claim issued against non individual defendant. 
```
[ ] Yes
[x] No
```
=> Do not display defendant date of birth page when CCJ is being requested against non individual defendants

src/main/views/includes/macros/partyDetails.njk
None
Display 'Not sure' on the check & send page if party date of birth is unknown
```
[ ] Yes
[x] No
```
=> Display 'Not sure' on the check & send page if party date of birth is unknown

Jenkinsfile
None
Correct path to the coverage HTML report
```
[ ] Yes
[x] No
```
=> Correct path to the coverage HTML report

package.json
Updated version of common-frontend
```
[ ] Yes
[x] No
```
=> ROC-2046: cmc-common-frontend updated to 1.7.3

package.json
https://tools.hmcts.net/jira/browse/ROC-749
This PR updates the sonar property.
```
[ ] Yes
[x] No
```
=> Update sonar property

src/main/features/ccj/views/date-of-birth.njk, src/main/features/ccj/views/payment-options.njk, src/main/public/js/analytics-custom-event-sender.js, src/main/views/includes/scripts.njk
https://tools.hmcts.net/jira/browse/ROC-2343
This story records both:
- defendant date of birth selection
- payment option selection
```
[ ] Yes
[x] No
```
=> Send custom GA events on defendant DOB selection or payment option selection

src/main/app.ts
As in title.
```
[ ] Yes
[x] No
```
=> Display dev error page in dockertests env

src/main/common/draft/draftMiddleware.ts
As the default is 10.
```
[ ] Yes
[x] No
```
=> Load 100 drafts by default

src/main/features/ccj/draft/draftCCJ.ts, src/main/features/response/guards/countyCourtJudgmentRequestedGuard.ts, src/main/features/response/index.ts, src/test/a11y/mocks.ts, src/test/features/response/routes/check-and-send.ts, src/test/features/response/routes/checks/ccj-requested-check.ts, src/test/features/response/routes/confirmation.ts, src/test/features/response/routes/counter-claim.ts, src/test/features/response/routes/defence-options.ts, src/test/features/response/routes/defendant-link-receiver.ts, src/test/features/response/routes/free-mediation.ts, src/test/features/response/routes/full-admission.ts, src/test/features/response/routes/incomplete-submission.ts, src/test/features/response/routes/more-time-confirmation.ts, src/test/features/response/routes/more-time-request.ts, src/test/features/response/routes/partial-admission.ts, src/test/features/response/routes/response-receipt.ts, src/test/features/response/routes/response-type.ts, src/test/features/response/routes/task-list.ts, src/test/features/response/routes/your-defence.ts, src/test/features/response/routes/your-details.ts, src/test/features/response/routes/your-dob.ts, src/test/features/response/routes/your-mobile.ts
https://tools.hmcts.net/jira/browse/ROC-2061
Added guard for response pages triggered when CCJ was requested
```
[ ] Yes
[x] No
```
=> ROC-2061: Add guard forbidding access to response journey when CCJ was requested

config/default.json, src/main/modules/nunjucks/index.ts, src/main/views/includes/phase_banner_beta.njk, src/main/views/includes/report_problem_link.njk
https://tools.hmcts.net/jira/browse/ROC-2501
=> ROC-2501: Add page url to survey links

config/custom-environment-variables.json, config/default.json, src/main/features/ccj/routes/confirmation.ts, src/main/features/ccj/views/confirmation.njk
https://tools.hmcts.net/jira/browse/ROC-2505
Content update to CCJ confirmation page.
```
[ ] Yes
[x] No
```
=> ROC-2505: CCJ confirmation page content update

src/main/features/ccj/form/models/paidAmount.ts, src/main/features/ccj/form/models/qualifiedDeclaration.ts, src/main/features/ccj/views/check-and-send.njk, src/main/features/ccj/views/paid-amount-summary.njk, src/main/features/ccj/views/paid-amount.njk, src/main/features/ccj/views/repayment-plan.njk
None
Small content changes requested during the feature review.
```
[ ] Yes
[x] No
```
=> CCJ: Update content after the feature review

src/main/features/response/form/models/responseType.ts, src/main/features/response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-2069
Updated check and send page to show do you owe money claimed section
```
[ ] Yes
[ x] No
```
=> ROC-2069: Update check-and-send page after changing response options

src/main/features/response/routes/timeline.ts, src/test/features/response/routes/timeline.ts
https://tools.hmcts.net/jira/browse/ROC-2161
on successful submit redirect to task list
```
[ ] Yes
[x] No
```
=> ROC-2161: redirect to task list

src/main/features/response/tasks/howMuchPaidTask.ts
https://tools.hmcts.net/jira/browse/ROC-1023
Removed unwanted console logs
```
[ ] Yes
[ x] No
```
=> ROC-1023 - refactor unwanted console logs

src/main/server.ts, src/test/features/response/draft/responseDraft.ts, src/test/features/response/tasks/howMuchPaidTask.ts, tslint.json
Logger should always be used for committed code, console.log is fine for
developing locally but it should never be merged
=> Ban console.*

config/custom-environment-variables.json, config/default.json, config/development.json, config/dockertests.json, config/mocha.json, src/main/features/response/draft/responseDraft.ts, src/main/features/response/helpers/taskListBuilder.ts, src/main/features/response/routes/task-list.ts
https://tools.hmcts.net/jira/browse/ROC-2161
Added feature toggle for partial admission
```
[x] Yes
[ ] No
```
=> ROC-2161: added feature toggle for partial admission pages

src/main/features/testing-support/paths.ts, src/main/features/testing-support/routes/delete-drafts.ts, src/main/features/testing-support/views/delete-drafts.njk, src/main/features/testing-support/views/index.njk
It allows to delete drafts so you don't need to submit the claim to remove it
=> Add testing support endpoint to delete drafts

src/main/common/router/routerFinder.ts
It would take some more work to be able to support more and I think this is probably enough for the general case
=> Allow one level directory deep with routerFinder

src/main/features/response/form/models/howMuchOwed.ts, src/main/features/response/routes/how-much-owed.ts, src/main/features/response/views/check-and-send.njk, src/main/features/validationErrors.ts
https://tools.hmcts.net/jira/browse/ROC-2311
Update check and send page, validation and fix total amount to display correct value
```
[ ] Yes
[ x] No
```
=> ROC-2311: Add fraction validation and add missing elements to check-and-send page

package.json
None
Increases timeout in route tests.
```
[ ] Yes
[x] No
```
=> Increase timeout in route tests to 4 seconds

src/main/features/claim/views/defendant-party-type-selection.njk
Added two thirds to party type
=> Add two thirds to party type

src/main/features/dashboard/routes/defendant.ts, src/main/features/dashboard/views/defendant.njk
https://tools.hmcts.net/jira/browse/ROC-2244
New Settle out of court link in defendant dashboard status page. 
```
[ ] Yes
[ x] No
```
=> ROC-2244: Add 'settle out of court' link to defendant dashboard status page

Jenkinsfile
https://tools.hmcts.net/jira/browse/ROC-2432
Run only citizen frontend integration tests.
```
[ ] Yes
[X] No
```
=> ROC-2432: Run only citizen frontend integration tests on builds

src/main/app/claims/claimStoreClient.ts, src/main/app/claims/offerClient.ts, src/main/features/offer/routes/declaration.ts, src/main/features/offer/routes/response.ts, src/main/features/offer/routes/your-offer.ts, src/test/features/offer/routes/declaration.ts, src/test/features/offer/routes/response.ts, src/test/http-mocks/claim-store.ts
https://tools.hmcts.net/jira/browse/ROC-2476
Calling API endpoints to store informations about 
```
[ ] Yes
[x] No
```
=> ROC-2476: calling api to reject or accept an offer

package.json, src/main/features/offer/views/response.njk, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-2475
Show/hide hint based on the user selection on claimant offer response page.
```
[ ] Yes
[ x] No
```
=> [ROC-2475] client offer acceptance options with show hide hint on selection

src/main/features/first-contact/index.ts, src/main/features/first-contact/routes/claim-summary.ts, src/test/features/first-contact/routes/checks/authorization-check.ts, src/test/features/first-contact/routes/claim-summary.ts
https://tools.hmcts.net/jira/browse/ROC-2122
=> ROC-2122 Logout pin user when responding

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-2253
New version of cmc-common-frontend: more statuses for claim / reponse
```
[ ] Yes
[x] No
```
=> ROC-2253: updated common fe version (status for rejected claim + no free mediation

Jenkinsfile
Explicitly do onPR and onMaster sections to be clear what runs where
=> ROC-2820: Refactor Jenkinsfile

config/dockertests.json
None
Enables features in docker env.
```
[ ] Yes
[x] No
```
=> Enable offers and statement of means in docker env

src/main/modules/helmet/modules/contentSecurityPolicy.ts
=> Forbid embedding the resource using frames

src/main/features/claim/routes/check-and-send.ts, src/main/features/claim/routes/total.ts
https://tools.hmcts.net/jira/browse/ROC-2847
Fix to show total amount on total page and check and send
```
[ ] Yes
[ x] No
```
=> ROC-2847- bugFix/total-claim-amount

src/main/app/pdf/issueReceipt.ts, src/main/app/pdf/responseReceipt.ts, src/main/resources/pdf/issueReceipt.njk, src/main/resources/pdf/responseReceipt.njk
Total claim amount was missing on issue receipts (both claim and response PDFs).
```
[ ] Yes
[X] No
```
=> Fix total claim amount on PDF issue receipts

Jenkinsfile
https://tools.hmcts.net/jira/browse/ROC-2484
```
[ ] Yes
[x] Certainly hope not
```
=> ROC-2484 Log build to influx

src/main/app/forms/models/interestTotal.ts, src/main/app/forms/models/totalAmount.ts, src/main/app/pdf/issueReceipt.ts, src/main/app/pdf/mappers/claimMapper.ts, src/main/app/pdf/mappers/interestMapper.ts, src/main/app/pdf/responseReceipt.ts, src/main/features/claim/routes/check-and-send.ts, src/main/features/claim/routes/total.ts, src/main/features/claim/views/total.njk, src/main/resources/pdf/issueReceipt.njk, src/main/resources/pdf/responseReceipt.njk
https://tools.hmcts.net/jira/browse/ROC-2856
```
[ ] Yes
[X] No
```
=> ROC-2856: Use correct total amount

src/main/features/response/routes/how-much-owed.ts
https://tools.hmcts.net/jira/browse/ROC-2897
Fix to the validation when amount entered is greater than total claim amount
```
[ ] Yes
[ x] No
```
=> ROC-2897: Fix amount range validation on 'How much you believe you owe' page

src/main/features/response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-2085
Update the check and page to include a link to text explanation 
```
[ ] Yes
[ x] No
```
=> ROC-2085: Add reason why defendant cannot pay full amount right now to CYA page

src/main/app/forms/models/itemInMultiRowForm.ts, src/main/app/forms/models/multiRowForm.ts, src/main/app/forms/models/multiRowFormItem.ts, src/main/features/response/form/models/statement-of-means/employerRow.ts, src/main/features/response/form/models/statement-of-means/employers.ts, src/test/features/response/form/models/statement-of-means/emoloyers.ts, src/test/features/response/form/models/statement-of-means/employerRow.ts
https://tools.hmcts.net/jira/browse/ROC-2559
Abstract class with common logic for multi row forms
```
[ ] Yes
[x] No
```
=> ROC-2559: common logic moved to abstract class for multi row forms

src/main/features/offer/views/your-offer.njk
https://tools.hmcts.net/jira/browse/ROC-2244
Content update on the make offer page to align it with prototype.
=> Update offer page to make it in sync with prototype

package.json, yarn.lock
None
PR uses new version of the library which displays email address on top in the support & help section
=> Update support widget to display email address on top

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/ROC-2864
Adds a CNP Jenkins pipeline file.
=> Add CNP pipeline file

.nsprc
https://tools.hmcts.net/jira/browse/ROC-2864
=> Remove comments from .nsprc as they break the file

src/main/features/offer/views/response.njk
https://tools.hmcts.net/jira/browse/ROC-2475
Small wording change to reflect change in the prototype.
=> ROC-2475: Update wording on offer response page

Jenkinsfile_CNP
=> Cleanup CNP jenkinsfile

src/main/features/response/tasks/whenWillYouPayTask.ts, src/main/features/response/views/check-and-send.njk, src/test/features/response/tasks/whenWillYouPayTask.ts, src/test/http-mocks/draft-store.ts
https://tools.hmcts.net/jira/browse/ROC-2559
Updated check and send
Updated isCompleted for task on task list page
=> ROC-2559: added logic for task.isCompleted and updated check and send page

package.json, src/main/features/claim/views/amount.njk, src/main/features/claim/views/reason.njk, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-2243
=> ROC-2243: Fix accessibility issues

src/main/app/forms/validation/validators/atLeastOnePopulatedRow.ts, src/main/app/forms/validation/validators/minNumberOfPopulatedRows.ts, src/main/features/response/draft/statementOfMeans.ts, src/main/features/response/form/models/statement-of-means/debtRow.ts, src/main/features/response/form/models/statement-of-means/debts.ts, src/main/features/response/paths.ts, src/main/features/response/routes/statement-of-means/bank-accounts.ts, src/main/features/response/routes/statement-of-means/debts.ts, src/main/features/response/tasks/whenWillYouPayTask.ts, src/main/features/response/views/statement-of-means/check-and-send.njk, src/main/features/response/views/statement-of-means/debts.njk, src/main/public/stylesheets/components/_form.scss, src/test/app/forms/validation/validators/atLeastOnePopulatedRow.ts, src/test/app/forms/validation/validators/minNumberOfPopoulatedRows.ts, src/test/features/response/form/models/statement-of-means/debtRow.ts, src/test/features/response/form/models/statement-of-means/debts.ts, src/test/features/response/routes/statement-of-means/debts.ts, src/test/features/response/tasks/whenWillYouPayTask.ts, src/test/http-mocks/draft-store.ts
https://tools.hmcts.net/jira/browse/ROC-2559
Added debts page
=> ROC-2559 debts page

src/main/app/forms/validation/validators/fractions.ts, src/main/app/forms/validation/validators/isBlank.ts, src/main/app/forms/validation/validators/isTodayOrInFuture.ts, src/main/app/forms/validation/validators/isValidLocalDate.ts, src/main/app/forms/validation/validators/isValidYearFormat.ts, src/main/app/forms/validation/validators/maximumAgeValidator.ts, src/main/app/forms/validation/validators/minTotal.ts, src/main/app/forms/validation/validators/minimumAgeValidator.ts, src/main/app/forms/validation/validators/mobilePhone.ts, src/main/app/forms/validation/validators/notInFuture.ts, src/test/app/forms/validation/validators/isInThePast.ts, src/test/app/forms/validation/validators/isNotBlankConstraint.ts, src/test/app/forms/validation/validators/isTodayOrInFutureConstraint.ts, src/test/app/forms/validation/validators/isValidLocalDate.ts, src/test/app/forms/validation/validators/minTotal.ts, src/test/app/forms/validation/validators/notInFutureConstraint.ts
=> Refactor: no nulls in validators. undefined instead

package.json, src/main/features/response/draft/statementOfMeans.ts, src/main/features/response/form/models/statement-of-means/courtOrderRow.ts, src/main/features/response/form/models/statement-of-means/courtOrders.ts, src/main/features/response/paths.ts, src/main/features/response/routes/statement-of-means/court-orders.ts, src/main/features/response/tasks/whenWillYouPayTask.ts, src/main/features/response/views/statement-of-means/bank-accounts.njk, src/main/features/response/views/statement-of-means/court-orders.njk, src/test/features/response/form/models/statement-of-means/courtOrderRow.ts, src/test/features/response/form/models/statement-of-means/courtOrders.ts, src/test/features/response/form/models/statement-of-means/debts.ts, src/test/features/response/routes/statement-of-means/court-orders.ts, src/test/features/response/tasks/whenWillYouPayTask.ts, src/test/http-mocks/draft-store.ts, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-2772
Added court orders page and tests
=> ROC-2772: court-orders page

src/main/features/response/views/statement-of-means/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-2772
Check and send page updated
=> ROC-2772: check and send page updated

src/main/features/response/views/check-and-send.njk, src/main/features/response/views/statement-of-means/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-2939
Updated check and send page so that "You defence" section is displayed.
I have also removed useless translations `t(...)` for numerals and date
=> ROC-2939: fixed check and send page

src/main/features/claim/views/claimant-party-type-selection.njk, src/main/features/claim/views/defendant-party-type-selection.njk, src/test/features/claim/routes/defendnat-party-type-selection.ts, yarn.lock
=> Update to content on the about you and about them selector pages

package.json, src/main/app/claims/models/defendantResponse.ts, src/main/app/claims/responseModelConverter.ts, src/main/features/response/draft/responseData.ts, src/test/app/claims/responseModelConverter.ts, src/test/data/entity/responseData.ts
[ROC-2703](https://tools.hmcts.net/jira/browse/ROC-2703)
This is just to make it work for now, thorough refactoring will follow.
=> ROC-2703: Update response model to reflect change in claim store

src/main/features/response/views/statement-of-means/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-2558
Unemployment status on check and send page
=> ROC-2558: updated check and send page for response so that unemployment status is displayed correctly

src/main/features/response/draft/statementOfMeans.ts, src/main/features/response/form/models/statement-of-means/amountDescriptionRow.ts, src/main/features/response/form/models/statement-of-means/monthlyIncome.ts, src/main/features/response/form/models/statement-of-means/monthlyIncomeRow.ts, src/main/features/response/paths.ts, src/main/features/response/routes/statement-of-means/debts.ts, src/main/features/response/routes/statement-of-means/monthly-income.ts, src/main/features/response/tasks/whenWillYouPayTask.ts, src/main/features/response/views/statement-of-means/check-and-send.njk, src/main/features/response/views/statement-of-means/monthly-income.njk, src/test/features/response/form/models/statement-of-means/amountDescriptionRow.ts, src/test/features/response/form/models/statement-of-means/monthlyIncome.ts, src/test/features/response/routes/statement-of-means/monthly-income.ts, src/test/features/response/tasks/whenWillYouPayTask.ts, src/test/http-mocks/draft-store.ts
https://tools.hmcts.net/jira/browse/ROC-2560
Monthly income page
=> ROC-2560: monthly income page

package.json, src/main/app/claims/models/defendantResponse.ts, src/main/app/pdf/responseReceipt.ts, yarn.lock
[ROC-2703](https://tools.hmcts.net/jira/browse/ROC-2703)
=> ROC-2703: Rename a field in response model to match claim store

.travis.yml
=> Remove travis greenkeeper stuff that did not work anyway

gulpfile.js, src/main/modules/helmet/modules/contentSecurityPolicy.ts, src/main/views/includes/scripts.njk
Thanks https://stackoverflow.com/a/46719128/4951015
=> Fix live reload

src/main/features/response/views/statement-of-means/monthly-expenses.njk
https://tools.hmcts.net/jira/browse/ROC-2560
Updated label
=> ROC-2560: update label

src/test/app/forms/models/dateOfBirth.ts, src/test/app/forms/models/payBySetDate.ts, src/test/app/forms/models/validationUtils.ts, src/test/features/ccj/routes/pay-by-set-date.ts, src/test/features/response/form/models/howMuchPaid.ts
None
This fixes flaky unit tests which started to fail in January due to the fact month `-1` does not exist.
=> Fix flaky unit tests

Jenkinsfile
Kevin said its fixed, let's test it
=> Reenable influxdb

src/main/public/js/postcode-lookup.js
Seems to stop the duplicate address options problem
=> Move clearing dropdown to last moment

src/main/public/js/postcode-lookup.js
If building name and building number are present now advancing building
number to the next line
=> ROC-2005 Handle buildingName and number being present

src/main/public/js/postcode-lookup.js
Fixes issues with enter manually sometimes being shown when it shouldn't and one case where validation messages were referencing hidden fields
=> ROC-2005 Postcode - fix ui state issues

src/main/app/claims/models/claim.ts, src/test/app/claims/models/claim.ts, src/test/http-mocks/claim-store.ts
https://tools.hmcts.net/jira/browse/ROC-2572
Calculating total amount (+interests) on server side
=> ROC-2572: calculate total amount on server side

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-3053
update common frontend version
=> ROC-3053 - Postcode lookup

src/main/features/claim/views/eligibility/not-eligible.njk
[ROC-3006](https://tools.hmcts.net/jira/browse/ROC-3006)
Tweak not-eligible content as per prototype
=> ROC-3006: Tweak not-eligible content as per prototype

src/main/app.ts, src/main/app/claims/claimMiddleware.ts, src/main/app/claims/claimStoreClient.ts, src/main/features/claim/routes/confirmation.ts, src/main/features/claim/routes/pay.ts, src/main/features/dashboard/routes/claimant.ts, src/main/features/dashboard/routes/defendant.ts, src/main/features/dashboard/routes/index.ts, src/main/features/first-contact/guards/claimReferenceMatchesGuard.ts, src/main/features/testing-support/testingSupportClient.ts, src/main/routes/receiver.ts
Only places I left out were interest calculation and isClaimLinked call
which is unauthenticated
=> ROC-3020 Send auth to backend

src/main/public/js/postcode-lookup.js
=> Fix postcode lookup IE 2

gulpfile.js, package.json, src/main/features/claim/views/claimant-company-details.njk, src/main/features/claim/views/claimant-individual-details.njk, src/main/features/claim/views/claimant-organisation-details.njk, src/main/features/claim/views/claimant-sole-trader-details.njk, src/main/features/claim/views/defendant-company-details.njk, src/main/features/claim/views/defendant-individual-details.njk, src/main/features/claim/views/defendant-organisation-details.njk, src/main/features/claim/views/defendant-sole-trader-details.njk, src/main/features/response/views/your-details.njk, src/main/views/postcode-lookup-client-scripts.njk, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-3135
Provides a polyfill to make postcode lookup client code work on IE9.
=> ROC-3135: Provide classlist polyfill

package.json
=> fix(package): update class-validator to version 0.8.1

src/main/features/response/form/models/statement-of-means/amountDescriptionRow.ts, src/main/features/response/form/models/statement-of-means/monthlyExpenses.ts, src/main/features/response/form/models/statement-of-means/monthlyIncome.ts, src/main/features/response/views/statement-of-means/monthly-expenses.njk, src/main/features/response/views/statement-of-means/monthly-income.njk, src/test/features/response/form/models/statement-of-means/amountDescriptionRow.ts, src/test/features/response/form/models/statement-of-means/monthlyExpenses.ts, src/test/features/response/form/models/statement-of-means/monthlyIncome.ts, src/test/features/response/routes/evidence.ts
https://tools.hmcts.net/jira/browse/ROC-3103
Updated error messages in order to making them more specific.
=> ROC-3103: update error messages for monthly income and expenses

src/main/app/fees/feesClient.ts, src/main/features/claim/routes/fees.ts, src/test/features/claim/routes/fees.ts
https://tools.hmcts.net/jira/browse/ROC-3144
Display error page when claim amount + interest > £10k
=> ROC-3144: redirect to error page for claim over 10k

package.json, src/main/common/interest.ts, src/main/features/ccj/routes/paid-amount-summary.ts, src/main/features/ccj/views/paid-amount-summary.njk, src/main/features/response/paths.ts, src/main/features/response/routes/claim-details.ts, src/main/features/response/routes/task-list.ts, src/main/features/response/views/claim-details.njk, src/main/features/response/views/task-list.njk, src/main/modules/nunjucks/index.ts, src/main/public/stylesheets/components/_form.scss, src/test/features/response/routes/claim-details.ts, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-3148
Add a view claim details page linked off of the dashboard
=> ROC-3148 show claim details

src/main/features/response/routes/claim-details.ts, src/main/features/response/views/claim-details.njk, src/main/modules/nunjucks/index.ts
https://tools.hmcts.net/jira/browse/ROC-3148
Remove global function call so that it shows the correct date
=> ROC-3148 view claim details

src/main/features/dashboard/views/claimant.njk, src/main/features/dashboard/views/defendant.njk, src/main/features/dashboard/views/index.njk, src/main/features/dashboard/views/macro/responseStatus.njk
https://tools.hmcts.net/jira/browse/ROC-2645
Move status macro to citizen-frontend
=> Move responseStatus to citizen-frontend

Jenkinsfile
=> Bigger node needed

src/main/views/macro/amountBreakdown.njk
https://tools.hmcts.net/jira/browse/ROC-3200
Fix wrong from date cause by bad merge
=> ROC-3200 Fix from date to use correct variable

src/main/modules/app-insights/index.ts
https://tools.hmcts.net/jira/browse/ROC-3224
Enables sending application log entries to App Insights as described [here](https://www.npmjs.com/package/applicationinsights#configuration).
=> Enable log entries in application insights

src/main/features/response/views/confirmation.njk
This was broken in the defendant content sweep, for some reason the feature toggle guard was removed
=> Add offer feature toggle guard

package.json, src/main/app/claims/claimStoreClient.ts, src/main/app/client/request.ts, src/main/app/forms/validation/validators/isCountrySupported.ts, src/main/app/pay/payClient.ts, src/main/app/postcode-lookup/clientFactory.ts, src/main/routes/postcode-lookup.ts, src/main/views/error_dev.njk, tsconfig.json, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-3255
Use `retryrequest` for all remaining clients.
=> ROC-3255: Retry remaining requests

docker-compose.functional-tests.yml, docker-compose.smoke-tests.yml
https://tools.hmcts.net/jira/browse/ROC-3269
I forgot to update docker entry points in functional and smoke tests compose files.
=> ROC-3269: Fix functional and smoke tests entry points

bin/run-functional-tests.sh, bin/run-smoke-tests.sh, docker-compose.functional-tests.yml
Make running against an env much easier
=> Add http proxy vars to functional tests

src/integration-test/tests/citizen/endToEnd/steps/helper.ts
Return promises that can be awaited/yielded.
=> Return promises to await/yield

infrastructure/main.tf
=> * Update support email

integration-tests.Dockerfile, saucelabs.conf.js
- reorder integration tests `Dockerfile` statements to save time,
- trim unwanted whitespace from configuration values.
=> Codecept related improvements

src/main/app/pay/payClient.ts
This PR fixes the request body for payment api.
=> Fix typo in payment request

Jenkinsfile_parameterized
=> Remove slack notification from sandbox

src/integration-test/tests/citizen/offers/offers_test.ts, src/main/features/first-contact/views/claim-summary.njk, src/main/features/response/views/confirmation.njk
=> Remove hardcoded Jan Clark

src/integration-test/tests/citizen/defence/pages/defendant-register.ts
https://github.com/hmcts/cmc-integration-tests/pull/169
=> Fix functional tests after idam content change..

src/main/features/ccj/views/check-and-send.njk, src/main/features/claim/views/check-and-send.njk, src/main/features/response/form/models/qualifiedStatementOfTruth.ts, src/main/features/response/form/models/statementOfTruth.ts, src/main/features/response/views/check-and-send.njk, src/main/views/macro/statementOfTruth.njk
https://tools.hmcts.net/jira/browse/ROC-3364
Provide additional content that should have been added in the content sweep PR.
=> ROC-3364: Provide additional content for response SOT

src/main/features/claim/routes/receipt.ts
https://tools.hmcts.net/jira/browse/ROC-3303
Change name of the pdf file name
- [x ] I have clicked through the running application to see if all changes I made actually work.
- [x ] No
=> ROC-3303 Change downloaded claim pdf filename

src/main/features/response/views/eligibility/send-your-response-by-email.njk
https://tools.hmcts.net/jira/browse/ROC-3375
https://tools.hmcts.net/jira/browse/ROC-3336
Update hand off pages with new content
=> ROC-3375 and ROC-3336 Defendant handoff guidance pages

src/main/features/offer/views/your-offer.njk
Removes blue background that wasn't suppose to be in "your-offer"
=> Removed description-block from offer page

infrastructure/aat.tfvars, infrastructure/variables.tf
BAT passed, approved by Clare and Kerry
Offers is a go
=> Enabling offers in production

src/integration-test/tests/citizen/offers/steps/offer.ts
Updated text to match prototype
=> Updated message

src/main/app/forms/validation/validationErrors.ts, src/main/features/claim/form/models/interestRate.ts, src/main/features/claim/form/models/interestStartDate.ts, src/test/features/claim/form/models/interestRate.ts, src/test/features/claim/form/models/interestStartDate.ts
https://tools.hmcts.net/jira/browse/ROC-3483
Validation error for interest rate reason was invalid. This fixes this problem.
=> ROC-3483: Fix validation message for interest rate reason

src/main/features/dashboard/views/claimant.njk
[ROC-3511](https://tools.hmcts.net/jira/browse/ROC-3511)
Fixed broken `Download Claim` link for claimant dashboard.
=> ROC-3511: Fix for download claim link

src/main/public/robots.txt
https://tools.hmcts.net/jira/browse/ROC-3480
This adds default robots.txt.
=> ROC-3480: Add robots.txt

src/main/app/drafts/draft-data/claimDraft.ts, src/main/features/testing-support/routes/create-claim-draft.ts, src/test/features/testing-support/create-claim-draft.ts
https://tools.hmcts.net/jira/browse/ROC-2874
Fixed the bug which didn't let you create more then 1 claim at a time.
=> ROC-2874: Create Claim Draft - Bug fix

infrastructure/preview.tfvars
AAT is now going to point to tactical preprod
Can't merge until IDAM have done a release into preprod though
=> Use tactical preprod for peered envs

src/main/app/models/yesNoOption.ts
None
This PR changes the way unknown Yes/No option is deserialised. Throwing error from deserialisation method makes validation middleware fail with unhandled promise rejection.
=> Deserialise YesNoOption as undefined if unknown option selected

src/integration-test/data/test-data.ts, types/integration-test-model.d.ts
Functional tests have been sending bad data which was breaking the
payment report
=> ROC-3570 Fix payment report

src/main/views/privacy-policy.njk
Removed repeated phrase in privacy policy
=> Removed repeated phrase in privacy policy

.gitignore
Ignore apple icon that is copied over in gulp
=> Ignore apple-touch icon

src/main/modules/helmet/modules/contentSecurityPolicy.ts
New inline js added from govukTemplate changes needs to be included in our CSP checks
=> Update content security policy to include new inline js

package.json
=> Restrict Node.js version to version older then 10.0.0

Jenkinsfile_CNP, Jenkinsfile_parameterized
https://tools.hmcts.net/jira/browse/ROC-3550
Added an `afterCheckout` hook to the pipeline to update the demo branches with latest master changes.
=> ROC-3550: Update demo on changes to master

src/integration-test/helpers/claimStoreHelper.ts, src/integration-test/helpers/clients/claimStoreClient.ts
https://tools.hmcts.net/jira/browse/ROC-3578
Updated functional test
=> ROC-3578: Fix functional tests

src/main/app/claims/isPastResponseDeadline.ts, src/main/app/claims/models/claim.ts, src/main/features/response/helpers/taskListBuilder.ts, src/main/features/response/routes/task-list.ts, src/test/app/claims/isPastResponseDeadline.ts, src/test/app/claims/models/claim.ts, src/test/features/response/helpers/taskListBuilder.ts, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-3738
We had a bug where the "Do you need more time to respond?" section was not available when defendant accessed the system on due day.
=> ROC-3738: Do you need more time to respond? not available on due day

src/main/app/claims/claimModelConverter.ts, src/test/app/claims/claimModelConverter.ts
Don't send `InterestDate` to the backend if 'no interest' option is selected.
=> Dont create interest date for no interest

package.json, src/integration-test/data/test-data.ts, src/integration-test/helpers/clients/claimStoreClient.ts, src/main/app/claims/claimStoreClient.ts, src/main/app/pay/payClient.ts, src/main/features/claim/routes/pay.ts, src/test/features/claim/routes/pay.ts, src/test/http-mocks/claim-store.ts, types/integration-test-model.d.ts
https://tools.hmcts.net/jira/browse/ROC-3730
New flow for submitting claims.
=> ROC-3730: Two steps for claim submission

package.json, src/main/features/first-contact/views/claim-reference.njk, src/main/views/enter-claim-number.njk, src/main/views/macro/claimReference.njk, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-3808
Create a macro for a claim reference input field
=> ROC-3808: Create claim reference macro

src/main/features/claim/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-3845
Missing bold label
=> ROC-3845 - Add bold label

config/default.json, src/main/features/eligibility/views/eligible.njk
Update default GA to point to non-prod and add event trigger
=> Add GA event

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/ROC-3940
Now that the hashi secrets are removed from the state the provider can be removed
=> ROC-3940 Remove hashi vault provider

src/main/features/ccj/views/confirmation.njk, src/main/features/dashboard/views/macro/claimStatus/ccjRequested.njk
https://tools.hmcts.net/jira/browse/ROC-3852
=> ROC-2852 Update to 14 days CCJ response

src/main/features/claim/views/total.njk
https://tools.hmcts.net/jira/browse/ROC-3923
Add hearing fee amount to total page
=> ROC-3923 Add hearing fee to total page

src/main/features/response/views/statement-of-means/court-orders.njk
https://tools.hmcts.net/jira/browse/ROC-3658
=> ROC-3658: Fix spelling error

src/main/app/drafts/draft-data/claimDraft.ts, src/main/features/testing-support/routes/create-claim-draft.ts
none
Create claim draft now puts the logged in users email in the defendant email field
=> Add user email to create claim draft

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/preview.tfvars, infrastructure/prod.tfvars
Somehow their certs expired and no one renewed them, migrating to cnp early to resolve
=> Move to CNP fees and payments (non prod only)

infrastructure/main.tf, infrastructure/variables.tf
none
Allows PR envs to be closed after PR is merged
```
[ ] Yes
[ ] No
```
=> Add common tags

src/main/app/utils/momentFormatter.ts, src/main/features/response/routes/full-admission/payment-date.ts, src/main/features/response/views/full-admission/payment-date.njk, src/main/modules/nunjucks/filters/dateFilter.ts, src/test/app/utils/momentFormatter.ts, src/test/modules/nunjucks/filters/dateFilter.ts
Update to correct date format as per UX request in sprint demo
=> Update hint as requested by UX

src/main/features/claimant-response/helpers/taskListBuilder.ts
https://tools.hmcts.net/jira/browse/ROC-4056
This PR renames the first task to make it consistent with other task list. Updating this after discussing with Pete.
=> Update content to make consistent

package.json, src/main/app/drafts/tasks/taskList.ts, src/main/features/claim/helpers/taskListBuilder.ts, src/main/features/claim/views/task-list.njk, src/main/features/claimant-response/helpers/taskListBuilder.ts, src/main/features/claimant-response/views/task-list.njk, src/main/features/response/helpers/taskListBuilder.ts, src/main/features/response/views/task-list.njk, src/main/public/stylesheets/components/_task-list.scss
=> Dynamic numeration of sections

src/main/features/response/form/models/statement-of-means/monthlyExpenses.ts, src/main/features/response/form/models/statement-of-means/monthlyIncome.ts, src/main/features/response/routes/statement-of-means/monthly-expenses.ts, src/main/features/response/routes/statement-of-means/monthly-income.ts, src/test/features/response/routes/statement-of-means/monthly-expenses.ts, src/test/features/response/routes/statement-of-means/monthly-income.ts
https://tools.hmcts.net/jira/browse/ROC-3859
Fix reset for JS off
=> ROC-3859 Reset income / expense fix

src/main/features/response/views/statement-of-means/monthly-expenses.njk
https://tools.hmcts.net/jira/browse/ROC-3859
Fix reset for expenses
=> ROC-3859 Fix reset issue

src/integration-test/tests/citizen/defence/pages/defendant-check-and-send.ts, src/integration-test/tests/citizen/defence/pages/defendant-task-list.ts, src/integration-test/tests/citizen/defence/steps/defence.ts, src/main/features/response/helpers/taskListBuilder.ts, src/main/features/response/views/check-and-send.njk, src/test/data/draft/responseDraft.ts, src/test/features/response/helpers/taskListBuilder.ts
https://tools.hmcts.net/jira/browse/ROC-3912
Free mediation as a separate section for all cases when it's displayed.
=> ROC-3912: extract free mediation to a separate section

src/main/features/response/form/models/whenDidYouPay.ts
https://tools.hmcts.net/jira/browse/ROC-4110
Fix validation message
=> ROC-4110 Update validation message

src/main/features/response/form/models/statement-of-means/expenseSource.ts, src/main/features/response/form/models/statement-of-means/incomeSource.ts, src/main/features/response/form/models/statement-of-means/monthlyExpenseType.ts, src/main/features/response/form/models/statement-of-means/monthlyExpenses.ts, src/main/features/response/form/models/statement-of-means/monthlyIncome.ts, src/main/features/response/form/models/statement-of-means/monthlyIncomeType.ts, src/main/features/response/views/statement-of-means/check-and-send.njk, src/main/features/response/views/statement-of-means/monthly-expenses.njk, src/main/features/response/views/statement-of-means/monthly-income.njk, src/main/modules/nunjucks/index.ts, src/test/app/common/calculate-monthly-income-expense/incomeExpenseSource.ts, src/test/app/common/calculate-monthly-income-expense/incomeExpenseSources.ts, src/test/features/response/form/models/statement-of-means/MonthlyExpenseType.ts, src/test/features/response/form/models/statement-of-means/MonthlyIncomeType.ts, src/test/features/response/form/models/statement-of-means/monthlyExpenses.ts, src/test/features/response/form/models/statement-of-means/monthlyIncome.ts, src/test/features/response/routes/statement-of-means/monthly-income.ts, src/test/features/response/tasks/statementOfMeansTask.ts
Introduces reusable income and expense types.
=> ROC-4038 Refactoring to introduce reusable income and expense types

src/integration-test/tests/citizen/ccj/ccj_test.ts, src/integration-test/tests/citizen/claim/enterDetails_test.ts, src/integration-test/tests/citizen/claim/fees_test.ts, src/integration-test/tests/citizen/claim/payment_test.ts, src/integration-test/tests/citizen/dashboard/dashboard_test.ts, src/integration-test/tests/citizen/defence/defence_claim_details_test.ts, src/integration-test/tests/citizen/defence/defence_handoff_test.ts, src/integration-test/tests/citizen/defence/defence_test.ts, src/integration-test/tests/citizen/defence/full_admission_test.ts, src/integration-test/tests/citizen/defence/part_admission_test.ts, src/integration-test/tests/citizen/endToEnd/endToend_test.ts, src/integration-test/tests/citizen/govukAccessRoutes/respondToClaim_test.ts, src/integration-test/tests/citizen/govukAccessRoutes/returnToClaim_test.ts, src/integration-test/tests/citizen/offers/offers_test.ts, src/integration-test/tests/citizen/testingSupport/testingSupport_test.ts, types/steps-override.d.ts
None
Retries failed scenarios up to 3 times to avoid failing the suit on erratic failures.
=> Retry E2E scenarios 3 times upon failure

src/main/features/response/views/your-mobile.njk
I changed 'contact' to 'phone' to match proto and cos it's better.
=> Change heading on your-mobile page

bin/run-functional-tests.sh, infrastructure/main.tf, infrastructure/sprod.tfvars, src/integration-test/tests/citizen/claim/steps/claim.ts
https://tools.hmcts.net/jira/browse/ROC-4121
https://tools.hmcts.net/jira/browse/ROC-4122
Setup sprod for perf testing
=> ROC-4121 Setup sprod

src/main/features/response/views/confirmation/full-defence-steps.njk
Ronan reviewed prod content and found is was not accurate. Change signed off by marc
=> Confirmation page content change

src/main/public/js/evidence-select-handler.js
https://tools.hmcts.net/jira/browse/ROC-4170
Original code attached the event handler to rows that existed when the document became ready. New code attaches a delegate event handler to the parent list of rows.
=> ROC-4170 Apply evidence type selection script to newly added rows

infrastructure/main.tf
None
Fixes configuration that point to feature toggle API on CNP.
=> Fix feature toggle API configuration

src/integration-test/tests/citizen/ccj/ccj_test.ts, src/integration-test/tests/citizen/ccj/pages/defendant-pay-by-instalments.ts, src/integration-test/tests/citizen/ccj/pages/defendant-pay-by-set-date.ts, src/integration-test/tests/citizen/ccj/steps/ccj.ts, src/integration-test/tests/citizen/defence/steps/defence.ts
This reverts commit 4b43e460bc8501beeab1eb1ee352f10e0e283d13.
None
Change broke e2e tests
=> Revert "Refactor - Duplication payment by set date & payment plan

src/main/features/response/views/statement-of-means/intro.njk
https://tools.hmcts.net/jira/browse/ROC-4277
=> [PREVIEW] - ROC-4277 - Statement of means intro missing content

src/integration-test/tests/citizen/offers/steps/offer.ts, src/main/features/dashboard/views/macro/claimStatus/claimFullyAdmitted.njk, src/main/features/dashboard/views/macro/claimStatus/claimPartAdmitted.njk, src/main/features/dashboard/views/macro/claimStatus/offerSubmitted.njk
=> [PREVIEW] - Update button content

src/main/features/response/views/check-and-send.njk, src/main/features/response/views/macro/check-and-send/admission.njk
https://tools.hmcts.net/jira/browse/ROC-4289
Add additional SoM page not displayed in SoM section of CYA 😠  to check for company and orgs
=> ROC-4289 Fix company CYA

Jenkinsfile_CNP
Changes to be merged manually today
=> Disable auto demo merge

src/main/features/claimant-response/views/settle-admitted.njk
https://tools.hmcts.net/jira/browse/ROC-4290
Show total amount till today instead of the claim amount breakdown total
=> ROC-4290 Reject defendant's partial admission hint shows full amount with fees

src/main/app/claims/ccjModelConverter.ts
https://tools.hmcts.net/jira/browse/ROC-4067
Bug with full admission where it was incorrectly putting claim amount as already paid.
=> ROC:4067 - fixing bug with full admission

src/main/common/components/ccj/paid-amount-summary.njk
[ROC-4309](https://tools.hmcts.net/jira/browse/ROC-4309)
=> ROC-4309: Bug fix amount for part admission ccj

src/main/app/claims/claimModelConverter.ts
Remove unneeded duplicate assignment.
=> Remove unneeded duplicate assignment

src/integration-test/tests/citizen/ccj/pages/defendant-paid-any-money.ts
This content was removed in a previous PR
=> ROC-4294 Remove verification of content

src/integration-test/tests/citizen/offers/steps/offer.ts
=> Update to new button content

src/integration-test/tests/citizen/offers/steps/offer.ts
=> One last content update in E2E

src/main/features/claimant-response/routes/defendants-response.ts, src/main/features/claimant-response/views/defendants-response.njk
This PR fixes the error on view defendant response page when payment option is immediate for part admission.
=> ROC-4338: Fix the view response page error for immediate payment option

src/test/app/common/payment-plan/paymentPlan.ts
https://tools.hmcts.net/jira/browse/ROC-4295
Fixed a failing tests in two-weekly payment tests
=> [REVIEW] fixed - test failing in 2 weekly payment tests

Jenkinsfile_CNP
=> Enable auto merge to demo

src/main/features/claimant-response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-4405
Fix court order payment plan error
- [ x] I have clicked through the running application to see if all changes I made actually work.
- [ x] No
=> ROC-4405 fix court order payment plan error in claimant response check and send

src/main/app/claims/isPastDeadline.ts, src/main/app/claims/isPastResponseDeadline.ts, src/main/app/claims/models/claim.ts, src/main/features/response/helpers/taskListBuilder.ts, src/test/app/claims/isPastResponseDeadline.ts, src/test/app/claims/models/claim.ts
Add in unit tests and refactor to use once instance of pastDeadline
=> Fix failing sonar test

src/integration-test/tests/citizen/defence/pages/defendant-task-list.ts, src/integration-test/tests/citizen/defence/steps/defence.ts
Update content to check for correct link
=> [PREVIEW] - Fix failing E2E test

src/main/app/claims/responseModelConverter.ts, src/test/data/entity/responseData.ts
None
This fixes missing conversion of Statement of Means / Other dependants spotted by @sabahirfan.
=> Add missing conversion of other dependants

src/test/app/common/payment-plan/paymentPlan.ts
=> ROC-4295 fixing test to avoid build failing on master

src/main/features/claimant-response/routes/accept-payment-method.ts, src/main/features/claimant-response/routes/defendants-response.ts, src/main/features/claimant-response/views/accept-payment-method.njk, src/main/features/claimant-response/views/defendants-response.njk, src/main/features/claimant-response/views/macro/repaymentPlanBlock.njk
https://tools.hmcts.net/jira/browse/ROC-4451
Simplify completion date and payment length code
=> ROC-4451: Simplify completion date and payment length code

src/main/features/claimant-response/routes/sign-settlement-agreement.ts, src/main/features/claimant-response/views/macro/termsOfAgreementTable.njk, src/main/features/claimant-response/views/sign-settlement-agreement.njk
[ROC-4055](https://tools.hmcts.net/jira/browse/ROC-4055)
This PR fixes the offer table on sign settlement table.
=> ROC-4055: Fix settlement offer table

src/main/common/components/payment-intention/model/paymentOption.ts
https://tools.hmcts.net/jira/browse/ROC-4049
Content change nothing much..
=> ROC-4049:Content changed since story developed

src/main/features/claimant-response/routes/payment-plan.ts
ROC-4593
Cover case where calculated means are non-positive; no court determination will be created.
=> ROC-4593 bug fix for non-positive determination of means

src/main/app/claims/converters/claimantResponseConverter.ts, src/main/features/claimant-response/routes/payment-date.ts, src/main/features/claimant-response/routes/payment-plan.ts
ROC-4593
Fix claimant response pay by set date when no disposable income
=> ROC-4593  Fix claimant response pay by set date when no disposable income

src/main/app/claims/converters/claimantResponseConverter.ts, src/main/common/helpers/paymentPlanHelper.ts, src/main/features/claimant-response/routes/payment-plan.ts, src/test/app/claims/converters/claimantResponseConverter.ts
ROC-4593
Reverted some previous changes that were trying to accommodate the defendant having no disposable income, which caused the court calculator to return `undefined`, which caused various later issues. This scenario will be dealt with in another story.
(a subset of possibilities - there are too many)
=> ROC-4593 Treat no disposable income as out of scope

src/main/resources/meansAllowance.json, src/test/data/draft/responseDraft.ts, src/test/data/entity/responseData.ts
ROC-4396
Dependant allowances were not being added due to a pluralisation issue in the nomenclature of the data file's categories
=> ROC-4396 correct name of dependant category

src/main/features/claimant-response/form/models/formaliseRepaymentPlanOption.ts, src/main/features/claimant-response/helpers/taskListBuilder.ts, src/main/features/claimant-response/views/accept-payment-method.njk, src/main/features/claimant-response/views/court-offer.njk, src/test/features/claimant-response/helpers/taskListBuilder.ts, src/test/features/claimant-response/routes/accept-payment-method.ts
=> Changes to make prod match FTTB

src/main/features/response/form/models/statement-of-means/priorityDebtType.ts, src/main/features/response/views/statement-of-means/priority-debts.njk
ROC-4406
Updated priority debt labels to match the prototype
=> ROC-4406 Correct priority debt categories' capitalisation to match prototype

src/main/features/claimant-response/routes/payment-date.ts
No Jira ticket
Rename a wrongly named variable in src/main/features/claimant-response/routes/payment-date.ts
=> Rename a wrongly named variable

src/main/features/claimant-response/routes/payment-option.ts
https://tools.hmcts.net/jira/browse/ROC-4318
payment option screen is incorrectly saving courtCalculatedPaymentIntention in draft which is now correcrted
=> ROC-4318-ImmediatePayment-PR2

src/main/features/claimant-response/helpers/settlementHelper.ts, src/main/features/claimant-response/views/check-and-send.njk, src/main/features/claimant-response/views/macro/termsOfAgreementTable.njk, src/test/features/claimant-response/helpers/settlementHelper.ts, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-4571
Update the settlement agreement, check and send pages with actual total amount in both instalment page and the set date page.
=> ROC-4571 Update Settlement agreement with total claim amount

src/main/resources/meansAllowance.json
https://tools.hmcts.net/jira/browse/ROC-4536
Changes made to allowance values used in court calculations
- [x ] No
=> ROC-4536 Update allowances for court calculations

src/main/app/claims/converters/claimantResponseConverter.ts, src/test/app/claims/converters/claimantResponseConverter.ts, src/test/data/draft/claimantPaymentIntentionDraft.ts
https://tools.hmcts.net/jira/browse/ROC-4690
added new units to increase coverage. reverted the claimantResponseConverter to its earlier state before ROC-4566
=> ROC-4690 Add Unit Tests for Different Claimant Response 

src/main/features/claimant-response/form/models/formaliseRepaymentPlanOption.ts, src/main/features/claimant-response/routes/rejection-reason.ts, src/test/features/claimant-response/form/models/formaliseRepaymentPlanOption.ts
https://tools.hmcts.net/jira/browse/ROC-4632
Set formaliseRepaymentPlan to REFER_TO_JUDGE when court decision is rejected in claimant response. 
Note: Doesn't cover scenario when disposable income is 0. @ckalista and I will discuss next week on how to handle this scenario. Currently it will fail when you submit at check and send. 
Scenarios where disposable income is not 0 will work with this PR.
=> ROC-4632: Refer to judge

package.json, yarn.lock
Sonar didn't pick up the dependabot PR so creating it manually.
=> Update Sinon Chai

infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
Disabling cache for some devops testing by Ben Neil on recommendation by Microsoft. After outages 22 Nov.
https://github.com/hmcts/cnp-module-webapp/blob/master/variables.tf
- [ X ] Yes - POSSIBLY!!!
=> Disable cache in demo and prod

src/main/app/idam/authorizationMiddleware.ts, src/main/app/idam/oAuthHelper.ts, src/main/features/eligibility/store.ts, src/main/features/first-contact/routes/claim-summary.ts, src/main/modules/csrf/index.ts, src/main/routes/logout.ts, src/main/routes/receiver.ts, src/test/routes/expectations.ts
remove lax from sameSite
https://hajekj.net/2018/08/31/beware-of-samesite-cookie-policy-in-asp-net-core-and-upcoming-ios-12/
=> iOS12 cookie bug

src/main/features/claimant-response/views/confirmation/accepted-payment-plan.njk
=> CPRC content change

src/main/features/claimant-response/routes/payment-option.ts, src/main/features/claimant-response/routes/payment-plan.ts
No Jira
For consistency, Math.round is refactored to use _.round in court determination files
=> change Math.round to Lodash round in court determination files

yarn.lock
Sonar failing to update dependencies with @ in the name
=> Update dependencies that are failing on sonar

src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
https://tools.hmcts.net/jira/browse/ROC-4401
Fixing broken e2e on master
=> ROC-4401: fixing broken e2e on master

src/main/features/claim/views/confirmation.njk
https://tools.hmcts.net/jira/browse/ROC-3887
=> ROC-3887 Update content for confirmation page

src/main/app/claims/models/claim.ts, src/main/features/dashboard/views/macro/caseHistory.njk, src/main/features/dashboard/views/macro/caseStatus.njk, src/main/features/dashboard/views/macro/claimStatus/paidInFullDefendant.njk
https://tools.hmcts.net/jira/browse/ROC-4336
=> ROC-4336 Paid in full defendants dashboard

src/main/routes/health.ts
https://tools.hmcts.net/jira/browse/ROC-4968
Removing idam www from health check.
=> rm -rf idam www from /health

src/main/features/claim/views/claimant-company-details.njk, src/main/features/claim/views/claimant-individual-details.njk, src/main/features/claim/views/claimant-organisation-details.njk, src/main/features/claim/views/claimant-sole-trader-details.njk, src/test/features/claim/routes/claimant-company-details.ts, src/test/features/claim/routes/claimant-individual-details.ts, src/test/features/claim/routes/claimant-organisation-details.ts, src/test/features/claim/routes/claimant-soleTrader-details.ts
https://tools.hmcts.net/jira/browse/ROC-4930
Content update
=> ROC-4930 Tell claimants details will be shared

src/main/features/claimant-response/routes/confirmation.ts, src/main/features/claimant-response/views/confirmation.njk
https://tools.hmcts.net/jira/browse/ROC-4967
Tell claimant they will get a copy of the CCJ
=> ROC-4967 Tell claimant they will get a copy of the CCJ

src/main/features/claimant-response/helpers/amountHelper.ts
Remove claim fee from settlement agreement
=> Part admit should not include claim fee for settlement agreement

src/main/features/claimant-response/routes/payment-plan.ts, src/test/common/helpers/paymentIntentionHelper.ts
https://tools.hmcts.net/jira/browse/ROC-4964
In case of defendant's negative income, display the claimant's repayment dates, all other repayment details must be as per the defendant's offer.
=> ROC-4964: Update first payment date

infrastructure/main.tf
From Jenkins build failure: 
```Invalid arm template
There's a bug in the azurerm provider, pin your azurerm provider to version 1.19.0 to fix, see PR-85 as an example on how to implement it Github issue tracking it GH-2507
Indication 1 
```
=> turn on admissions aat (fix)

src/main/features/dashboard/views/macro/caseHistory.njk, src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
https://tools.hmcts.net/jira/browse/ROC-4567
Claim details page fix which got introduced by other story
=> ROC-4567: Claim details page Bug fix which got introduced by other story

src/main/features/dashboard/views/macro/caseHistory.njk
https://tools.hmcts.net/jira/browse/ROC-5057
Fix variable name
=> ROC-5057 Paid in full not appearing

src/main/features/claimant-response/views/defendants-response.njk, src/main/features/eligibility/views/claim-is-for-tenancy-deposit.njk, src/main/features/eligibility/views/claim-type.njk, src/main/features/eligibility/views/claim-value.njk, src/main/features/eligibility/views/claimant-address.njk, src/main/features/eligibility/views/defendant-address.njk, src/main/features/eligibility/views/defendant-age.njk, src/main/features/eligibility/views/government-department.njk, src/main/features/eligibility/views/help-with-fees.njk, src/main/features/eligibility/views/over-18.njk, src/main/features/eligibility/views/single-defendant.njk, src/main/features/first-contact/views/claim-reference.njk, src/main/features/mediation/views/how-mediation-works.njk, src/main/features/offer/views/response.njk, src/main/features/response/views/more-time-confirmation.njk, src/main/features/response/views/send-company-financial-details.njk, src/main/features/response/views/statement-of-means/intro.njk, src/main/views/enter-claim-number.njk, src/main/views/no-claim-number.njk
https://tools.hmcts.net/jira/browse/ROC-5095
Change content of buttons and use default value across the site
=> ROC-5095 - Change button text

Dockerfile
[CNP-1109](https://tools.hmcts.net/jira/browse/CNP-1109)
Hello, this PR adds the following enhancements:
- improve the ordering of the docker image build layer
- prepare for future ACR cache optimisations.
This is part of a general pipelines optimisations initiative and should not impact the current builds.
- [NA] Unit tests added where applicable
- [NA] Route tests added for new pages
- [NA] New pages included in a11y tests
- [NA] Task list and task completeness checks updated
- [NA] Check and send page updated
- [NA] Routes, page content and page flows of new features are toggled 
- [NA] UI changes look good on mobile
- [?] Required Google Analytics events are being sent
=> Optimise docker image build layers

src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
https://tools.hmcts.net/jira/browse/ROC-5123
Update content to match prototype
=> ROC-5123 Wrong content

src/main/features/claimant-response/routes/check-and-send.ts, src/main/features/claimant-response/routes/settle-admitted.ts, src/main/features/claimant-response/views/settle-admitted.njk
https://tools.hmcts.net/jira/browse/ROC-5142
Remove hint text when pay immediately and return payment intention
=> ROC-5142 Part admit pay immediately check-and-send page

src/test/features/claimant-response/routes/payment-date.ts, src/test/http-mocks/claim-store.ts
https://tools.hmcts.net/jira/browse/ROC-5033 
Added route tests for payment date route. This is first PR, other PR's to follow
=> ROC-5033: Added payment date route tests - PR1

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.template.yaml
Update helm chart to use rpe feature-toggle chart
=> update feature-toggle-api chart

yarn.lock
Dependabot can't update it due to the @ in the branch name.
=> Update @types/node version

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-4692
Dependency bump
=> ROC-4692 Bump cmc-validators dependency to 0.2.2

charts/cmc-citizen-frontend/values.template.yaml
https://tools.hmcts.net/jira/browse/ROC-5251
Not seeing expected behaviour for admissions when manually using AKS environments. Not an issue for functional tests because claims all setup via helper client.
=> ROC-5251: fix feature-toggle service port

Jenkinsfile_nightly, security.sh
https://tools.hmcts.net/jira/browse/ROC-4146
Setting up nightly security scanning
=> set up cmc citizen frontend security scan

src/main/app/claims/converters/claimantResponseConverter.ts, src/main/app/claims/models/claim.ts, src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedClaimant.njk, src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedDefendant.njk, src/test/app/claims/converters/claimantResponseConverter.ts, src/test/app/claims/models/claim.ts
https://tools.hmcts.net/jira/browse/ROC-5151
we don't use rejection reason within claimantResponse.courtDetermination.rejectionReason but reuse level above rejectionReason across various flows of claimantResponse - 
https://github.com/hmcts/cmc-citizen-frontend/blob/master/src/main/features/claimant-response/routes/rejection-reason.ts
=> ROC-5151: Rejection reason and dashboard status fix & dashboard status

Jenkinsfile_CNP
Successfully tested on claim-store.
=>  Fix git push to demo

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/ROC-4146
Missing a closing `}` - also fixed formating.
=> Fix nightly Jenkins security scanning

src/main/features/mediation/views/free-mediation.njk
=> Added one word ('free') to mediation button

src/main/features/mediation/views/how-mediation-works.njk
Changed 'If either party breaks the terms, the other party can apply to the court to enforce them'
to
'If either party breaks the terms, the other party can go back to the court to ask for a judgment or hearing'
=> One mediation text change

Jenkinsfile_nightly, docker-compose.functional-tests.yml, docker-compose.nightly-functional-tests.yml
https://tools.hmcts.net/jira/browse/ROC-5033
changing nightly pipeline config
=> ROC-5033:Nightly pipeline

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/ROC-5033
Jenkins Nightly Config changes
=> ROC-5033:Jenkins Nightly Config changes

Jenkinsfile_nightly, docker-compose.functional-tests.yml, docker-compose.nightly-functional-tests.yml, docker-compose.smoke-tests.yml, src/integration-test/tests/citizen/claim/enterDetails_test.ts
Change nightly to run everything
=> Change nightly to run everything

Jenkinsfile_nightly
=> Increase nightly run timeout

yarn.lock
Failed due to sonar branch restrictions
=> Update dependancy @Types/jsonwebtoken

Jenkinsfile_CNP
Functional tests now within 40mins default - revert back to master branch for jenkins library.
=> Revert back to master for jenkins library

src/main/features/response/routes/your-dob.ts, src/test/features/response/routes/your-dob.ts
https://tools.hmcts.net/jira/browse/ROC-5133
=> ROC-5133 Do not redirect to under 18 page

src/main/features/claim/views/total.njk
=> Content - fixed typo

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/values.template.yaml
https://tools.hmcts.net/jira/browse/ROC-5368
Fix type in feature-toggle service tag.
=> ROC-5368: fix helm tag typo

src/main/app/claims/models/claim.ts, src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk, src/test/app/claims/models/claim.ts, src/test/data/entity/responseData.ts, src/test/features/dashboard/routes/index.ts
https://tools.hmcts.net/jira/browse/ROC-5349
Fix dashboard/claim status to correctly report states paid accepted and rejected states.
=> ROC-5349: Defendant loop when part admit claim is rejected

Jenkinsfile_CNP
Pipeline is broken since changes to point to SIDAM. Manually tested with curl and PR https://build.platform.hmcts.net/job/HMCTS_CMC/job/cmc-citizen-frontend/view/change-requests/job/PR-1493/.
This manually adds whitelisting URL to SIDAM. Temporary fix I assume.
=> Fix pipeline with SIDAM

src/main/features/dashboard/index.ts, src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForClaimant.njk
https://tools.hmcts.net/jira/browse/ROC-5437
We were incorrectly extracting the date from the claim, so it was not showing up on the claim details (claimant) pages
=> ROC-5437 Extract date from claim response

Jenkinsfile_CNP, charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.template.yaml
Changes required for Helm product chart. Removes horrible admin/password from explicitly defining in values.yaml.
=> Helm chart changes: feature-toggle-importer

src/main/common/components/free-mediation/freeMediationCheckAndSendBlock.njk, src/main/common/components/free-mediation/freeMediationTask.ts, src/main/features/mediation/form/models/CanWeUseCompany.ts, src/main/features/mediation/routes/free-mediation.ts, src/main/features/mediation/routes/will-you-try-mediation.ts, src/main/features/mediation/views/can-we-use.njk, src/main/features/mediation/views/free-mediation.njk, src/main/features/mediation/views/will-you-try-mediation.njk, src/test/common/components/free-mediation/freeMediationTask.ts
https://tools.hmcts.net/jira/browse/ROC-5373
Content updates for the claimant response journey
=> ROC-5373 Claimant response mediation

src/main/app/claims/models/claim.ts
https://tools.hmcts.net/jira/browse/ROC-5577
Bug identified in a claim status `get`ter that was supposed to be just for full admission responses but wasn't actually verifying as such.
=> ROC-5577 PA dashboard showing as FA

package.json, yarn.lock
=> Revert codecept upgrade

infrastructure/main.tf
=> Remove explicit Azure Provider version

saucelabs.conf.js, src/integration-test/helpers/saucelabsReporter.js
https://tools.hmcts.net/jira/browse/ROC-4116
- [ x] No
=> ROC-4116 Cross browser test fix

package.json, yarn.lock
newer versions of codecept don't run the e2e tests
=> Fix codecept version

src/main/app/claims/models/claim.ts, src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk, src/test/data/entity/claimantResponseData.ts, src/test/features/dashboard/routes/index.ts
https://tools.hmcts.net/jira/browse/ROC-5530
Fix failing dashboard tests
=> ROC-5530 defendant part admission dashboard

charts/cmc-citizen-frontend/values.yaml
reduce CPU requests (use default in NodeJS chart)
=> use default CPU requests

Jenkinsfile_nightly
Back to square one with the env vars...both are required - my bad, sorry Sumit 🙈
=> Add another missing env var for nightly

src/main/app/claims/models/claim.ts, src/main/features/ccj/guards/ccjGuard.ts, src/main/features/ccj/routes/check-and-send.ts, src/main/features/ccj/routes/paid-amount-summary.ts, src/main/features/ccj/views/check-and-send.njk, src/main/features/claimant-response/helpers/taskListBuilder.ts, src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk, src/test/features/ccj/routes/check-and-send.ts
https://tools.hmcts.net/jira/browse/ROC-5701
Show formalise option when a claimant accepts a business admission
=> ROC-5701 Claimant accepts business admission

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
PRs currently broken with Postgres error. Fixed downstream in `chart-java` and `rpe-feature-toggle-api` charts.
=> Bump feature-toggle-api chart version

src/main/app/claims/models/claim.ts
https://tools.hmcts.net/jira/browse/ROC-5842
Revert change for part admission
=> ROC-5842  - Part admit dashboard issue

src/main/features/ccj/views/confirmation-ccj.njk, src/main/features/ccj/views/confirmation-redetermination.njk, src/main/features/claim/views/confirmation.njk, src/main/features/claimant-response/views/confirmation.njk, src/main/features/offer/views/settled.njk, src/main/features/paid-in-full/views/confirmation.njk, src/main/features/response/views/confirmation.njk, src/main/features/settlement-agreement/views/settlement-agreement-confirmation.njk
https://tools.hmcts.net/jira/browse/ROC-5819
Change content of button to continue
=> ROC-5819 Change content of button to continue

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml
Minor change - bump nodejs version.
=> Bump nodejs chart

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
For HMCTS Demo primarily but will also stop some AKS envs getting 'stuck' and not deleting fully.
=> Bump idam-pr chart version

src/main/app/idam/idamClient.ts, src/test/http-mocks/idam.ts, src/test/routes/receiver.ts
https://tools.hmcts.net/jira/browse/ROC-5903
Propagate errors from code exchange up to the `receiver` controller code for graceful handling.
=> ROC-5903 graceless login receiver failure

Jenkinsfile_CNP, charts/cmc-citizen-frontend/Chart.yaml
Bump chart version so all minor releases of dependencies (e.g. IDAM PR chart) are updated.
=> Update helm dependencies

src/main/features/directions-questionnaire/views/other-witnesses.njk
https://tools.hmcts.net/jira/browse/ROC-5980
Update content to match prototype
=> ROC-5980 Other witness content update

src/main/features/directions-questionnaire/views/self-witness.njk
https://tools.hmcts.net/jira/browse/ROC-5979
Content update
=> ROC-5979 Self witness content update

src/main/common/components/free-mediation/freeMediationCheckAndSendBlock.njk, src/main/common/components/free-mediation/howFreeMediationWorks.njk, src/main/common/utils/freeMediationUtil.ts, src/main/features/mediation/draft/mediationDraft.ts, src/main/features/mediation/paths.ts, src/main/features/mediation/routes/can-we-use-company.ts, src/main/features/mediation/routes/continue-without-mediation.ts, src/main/features/mediation/routes/how-mediation-works.ts, src/main/features/mediation/routes/mediation-agreement.ts, src/main/features/mediation/routes/mediation-disagreement.ts, src/main/features/mediation/views/can-we-use.njk, src/main/features/mediation/views/continue-without-mediation.njk, src/main/features/mediation/views/how-mediation-works.njk, src/main/features/mediation/views/mediation-disagreement.njk, src/test/common/utils/freeMediationUtil.ts, src/test/features/mediation/routes/how-mediation-works.ts, src/test/features/mediation/routes/mediation-agreement.ts, src/test/features/mediation/routes/mediation-disagreement.ts, src/test/http-mocks/draft-store.ts
=> ROC-5409 pull out mediation to make smaller PRs

Dockerfile
Move Docker base image to use HMCTS public ACR repo.
=> Update base image to use HMCTS public ACR

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml
=> Update Helm chart to use hmctspublic

src/main/app/claims/models/directions-questionnaire/directionsQuestionnaire.ts, src/main/app/claims/models/response/fullDefenceResponse.ts, src/main/app/claims/models/response/partialAdmissionResponse.ts, src/test/app/claims/models/directions-questionnaire/directionsQuestionnaire.ts, src/test/app/claims/responseModelConverter.ts
https://tools.hmcts.net/jira/browse/ROC-5387
Response converter test file is replaced with original file in one of the merge conflicts. This PR is to retain response converter and make sure its working and covered all DQ's
=> ROC-5387 Added missing response converter test file

src/main/app/claims/models/claim.ts
https://tools.hmcts.net/jira/browse/ROC-6059
Update logic for ccj eligibility to check for acceptation of the part admission
=> ROC-6059 Part admission incorrect dashboard 

config/default.json, src/main/common/components/free-mediation/freeMediationTask.ts, src/main/features/claim/routes/pay.ts, src/main/features/claimant-response/index.ts, src/main/features/claimant-response/routes/intention-to-proceed.ts, src/main/features/claimant-response/views/confirmation.njk, src/main/features/claimant-response/views/defendants-response.njk, src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk, src/main/modules/nunjucks/index.ts, src/test/features/claimant-response/routes/intention-to-proceed.ts
https://tools.hmcts.net/jira/browse/ROC-5373
Move out from large PR to make it smaller
=> ROC-5373 Mediation smaller PR

src/main/features/claimant-response/views/confirmation.njk
https://tools.hmcts.net/jira/browse/ROC-6029
Update evaluation to check for correct value
=> ROC-6029 Claimant response confirmation mediation not showing

src/main/features/dashboard/views/macro/claimStatus/statesPaidAccepted.njk
https://tools.hmcts.net/jira/browse/ROC-6026
Update to use correct variable
=> ROC-6026 Wrong amount on states paid claim details

src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
https://tools.hmcts.net/jira/browse/ROC-6038
Update to use the latest version of the dashboard
=> ROC-6038 Claimant response dashboard wrong content

charts/cmc-citizen-frontend/values.preview.template.yaml, config/default.json
Reset timeout back to 10secs for production and increase only for PRs.
=> Revert timeout change - increase for PR only

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf
The increased timeout works on PRs - this also adds to AAT so master pipeline will benefit too.
=> Add http_timeout for aat functional testing on master

src/main/features/response/views/confirmation/part-admission-steps.njk, src/main/features/response/views/confirmation/part-admission.njk
https://tools.hmcts.net/jira/browse/ROC-6062
Add logic to show mediation information
=> ROC-6062 Part admit confirmation page

src/main/features/claimant-response/routes/defendants-response.ts, src/main/features/claimant-response/views/defendants-response.njk
https://tools.hmcts.net/jira/browse/ROC-6097
Update evaluation logic for what gets shown
=> ROC-6097 View defendants response

src/main/features/claimant-response/filters/monthly-amount-view-filter.ts, src/test/features/claimant-response/filters/monthly-amount-view-filter.ts
https://tools.hmcts.net/jira/browse/ROC-6105
Update Monthly Amount filter to accept a zero amount
=> ROC-6105 Allow zero declared income amount

.dockerignore, acb.tpl.yaml, docker-compose.functional-tests.yml, docker-compose.nightly-functional-tests.yml, docker-compose.smoke-tests.yml, docker-compose.yml, integration-tests.Dockerfile
Moving from dockerhub to hmctspublic.
=> Build integration tests image in hmctspublic

src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk, src/test/data/entity/fullDefenceData.ts, src/test/data/entity/responseData.ts, src/test/features/dashboard/routes/claimStatus/full-defence.ts, src/test/features/dashboard/routes/claimStatus/states-paid.ts, src/test/features/dashboard/routes/dashboard/states-paid.ts
https://tools.hmcts.net/jira/browse/ROC-6082
Add in dq and non dq option for states paid defence
=> ROC-6082 States paid dashboard issue for defendant

src/main/features/claim/views/new-features-consent.njk, src/test/features/claim/routes/new-features-consent.ts
=> RonanContentChange

src/test/features/claimant-response/routes/payment-date.ts
https://tools.hmcts.net/jira/browse/ROC-6171
Update test data so it won't fail again for another 20 years.
=> ROC-6171 Fix pay-date test (for 20 years)

src/main/features/directions-questionnaire/views/self-witness.njk
Changed 'going to' a hearing to 'speaking at' a hearing, as per judge's comments.
=> ROC-6155 - Self witness content change

src/main/features/directions-questionnaire/views/expert-guidance.njk
Changed 'will' to 'may' based on feedback from the judge.
=> ROC-5945 - Expert guidance content change

src/test/app/claims/converters/claimantResponseConverter.ts, src/test/app/claims/models/claim.ts, src/test/features/claimant-response/helpers/directionsQuestionnaireHelper.ts, src/test/features/claimant-response/routes/check-and-send.ts, src/test/features/dashboard/routes/claimStatus/full-defence.ts, src/test/features/directions-questionnaire/routes/expert-evidence.ts, src/test/features/directions-questionnaire/routes/expert-guidance.ts, src/test/features/directions-questionnaire/routes/expert-reports.ts, src/test/features/directions-questionnaire/routes/expert.ts, src/test/features/directions-questionnaire/routes/hearing-dates-picker.ts, src/test/features/directions-questionnaire/routes/hearing-dates.ts, src/test/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts, src/test/features/directions-questionnaire/routes/hearing-location.ts, src/test/features/directions-questionnaire/routes/other-witnesses.ts, src/test/features/directions-questionnaire/routes/permission-for-expert.ts, src/test/features/directions-questionnaire/routes/self-witness.ts, src/test/features/directions-questionnaire/routes/support-required.ts, src/test/features/directions-questionnaire/routes/why-expert-is-needed.ts, src/test/features/orders/routes/disagree-with-order.ts, src/test/features/response/helpers/taskListBuilder.ts, src/test/features/response/routes/check-and-send.ts
https://tools.hmcts.net/jira/browse/ROC-6180
Fix DQ unit tests in master
=> ROC-6180: Fix DQ unit tests and route tests in master

src/main/features/claimant-response/routes/check-and-send.ts, src/main/features/claimant-response/routes/intention-to-proceed.ts, src/main/features/claimant-response/views/check-and-send.njk, src/main/features/claimant-response/views/confirmation.njk, src/main/features/response/views/confirmation/full-defence-steps.njk, src/test/features/response/routes/confirmation.ts
https://tools.hmcts.net/jira/browse/ROC-6154
Update content to match prototype and fix check-and-send logic
=> ROC-6154 Intention to proceed confirmation content

src/main/features/directions-questionnaire/views/support-required.njk, src/main/public/stylesheets/components/_income-expense-source.scss
https://tools.hmcts.net/jira/browse/ROC-6166
=> ROC-6166 Re-order list of support items

src/main/app/claims/claimStoreClient.ts, src/main/app/claims/models/reviewOrder.ts, src/main/app/claims/ordersConverter.ts, src/main/features/orders/routes/disagree-with-order.ts, src/test/app/claims/claimStoreClient.ts, src/test/app/claims/models/reviewOrder.ts, src/test/app/claims/ordersConverter.ts, src/test/features/orders/routes/disagree-with-order.ts, src/test/http-mocks/claim-store.ts, src/test/http-mocks/draft-store.ts
https://tools.hmcts.net/jira/browse/ROC-5823
Orders convertor and save
- [ *] Unit tests added where applicable
- [ *] Route tests added for new pages
- [* ] I have clicked through the running application to see if all changes I made actually work.
- [ *] No
=> ROC:5823-Orders convertor and save

Jenkinsfile_CNP
To disable auto-merge to Demo during the Bug Bash session
- [x ] No
=> disable auto merge to demo

Jenkinsfile_CNP
enable auto merge to demo
- [x ] No
=> enable auto merge

src/main/common/components/free-mediation/freeMediationCheckAndSendBlock.njk, src/main/features/claimant-response/views/check-and-send.njk, src/main/features/response/views/check-and-send.njk, src/main/features/response/views/confirmation/full-defence-steps.njk, src/test/features/response/routes/confirmation.ts
https://tools.hmcts.net/jira/browse/ROC-5373
The bug fixes from the bug bash can be found here. Mainly content changes
=> ROC-5373: Bug Bash

src/main/app/common/signatureType.ts, src/main/features/response/form/models/qualifiedStatementOfTruth.ts, src/main/features/response/routes/check-and-send.ts, src/main/views/macro/statementOfTruth.njk
https://tools.hmcts.net/jira/browse/ROC-6177
Statement of truth for the business defendant.
=> ROC-6177-Fixed statement of truth for the business defendant

src/main/features/claimant-response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-6140
Update logic of already paid and dispute
=> ROC-6140 Claimant response check and send

src/main/features/response/views/confirmation/part-admission-steps.njk, src/main/features/response/views/confirmation/part-admission.njk, src/test/data/entity/responseData.ts, src/test/features/response/routes/confirmation.ts, src/test/http-mocks/claim-store.ts
https://tools.hmcts.net/jira/browse/ROC-5422
=> ROC-5422 Part admission mediation confirmation screen

src/main/features/directions-questionnaire/forms/models/exceptionalCircumstances.ts, src/test/features/directions-questionnaire/form/models/exceptionalCircumstances.ts, src/test/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
https://tools.hmcts.net/jira/browse/ROC-6201
Fix for validation of exceptional circumstance reason only when the YES is selected.
=> ROC-6201 Fix for exceptional circumstance only when YES

src/main/features/mediation/views/can-we-use.njk
Added direct phone line info to match features to be built - after noticing difference in bugbash and checking with product.
=> Content - phone line should be direct

src/main/app/claims/models/reviewOrder.ts, src/main/app/claims/ordersConverter.ts, src/test/app/claims/ordersConverter.ts
https://tools.hmcts.net/jira/browse/ROC-6307
Review Order submit page issue fixed
- [* ] Unit tests added where applicable
- [* ] No
=> ROC:6307: Fix review order converter bug

src/main/common/components/free-mediation/freeMediationTask.ts, src/main/features/claimant-response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-6311
Update logic to show free mediation section
=> ROC-6311 Mediation not showing on states paid

src/main/features/directions-questionnaire/views/hearing-location.njk
https://tools.hmcts.net/jira/browse/ROC-6266
Remove extra text under court name text box ('Do you want to choose')
=> ROC-6266: Remove erroneous text under court name text box

src/main/features/directions-questionnaire/views/hearing-location.njk
https://tools.hmcts.net/jira/browse/ROC-6256
Underline text for court facilities
=> ROC-6256 Underline court facilities link

src/main/features/claim/views/check-and-send.njk, src/main/features/claimant-response/routes/check-and-send.ts, src/main/features/response/routes/check-and-send.ts, src/main/views/macro/statementOfTruth.njk
https://tools.hmcts.net/jira/browse/ROC-6240
=> ROC-6240 Statement of truth content change

Jenkinsfile_nightly
Nightly Jenkins file should be configured exactly as per AAT.
=> Fix nightly's

src/main/features/claimant-response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-6311
Show mediation for already paid less than the amount
=> ROC-6311 - States paid less than the amount mediation not showing

src/main/app/claims/models/claim.ts, src/main/features/dashboard/views/macro/caseHistory.njk, src/main/features/dashboard/views/macro/caseStatus.njk, src/main/features/dashboard/views/macro/claimStatus/orders.njk, src/test/features/dashboard/routes/dashboard/orders.ts
https://tools.hmcts.net/jira/browse/ROC-6359
Update dashboard that is shown after review has been requested
=> ROC-6359 - Review requested dashboard status

src/main/app/claims/models/claim.ts, src/main/features/dashboard/routes/claimant.ts, src/main/features/dashboard/routes/defendant.ts, src/main/features/dashboard/views/claimant.njk, src/main/features/dashboard/views/defendant.njk, src/main/features/dashboard/views/macro/caseHistory.njk, src/main/features/dashboard/views/macro/claimStatus/orders.njk, src/test/features/dashboard/routes/claimStatus/orders.ts, src/test/features/dashboard/routes/dashboard/orders.ts
https://tools.hmcts.net/jira/browse/ROC-6373
Use the correct date for review order deadline
=> ROC-6373 Review order respond date

src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
https://tools.hmcts.net/jira/browse/ROC-6404
Dashboard status is incorrect when defence is rejected without mediation.
=> ROC-6404: Incorrect claimant dashboard status

src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
https://tools.hmcts.net/jira/browse/ROC-6403
=> ROC-6403 Dashboard content

src/main/features/directions-questionnaire/views/hearing-location.njk
https://tools.hmcts.net/jira/browse/ROC-6399
Update logic for showing correct content
=> ROC-6399 Hearing location content

src/main/app/claims/models/claim.ts, src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk, src/main/public/js/date-picker.js
https://tools.hmcts.net/jira/browse/ROC-6370
Update logic for business to check for DQ on case
=> ROC-6370 Defendant dashboard

src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
https://tools.hmcts.net/jira/browse/ROC-6418
=> ROC-6418 DQ offline dashboard and claim details

src/main/features/response/routes/response-type.ts, src/main/features/response/views/check-and-send.njk, src/test/features/response/routes/response-type.ts
https://tools.hmcts.net/jira/browse/ROC-6431
Show mediation when there is a draft object
=> ROC-6431 Check and send not showing mediation

src/main/features/mediation/routes/mediation-agreement.ts
https://tools.hmcts.net/jira/browse/ROC-6412
Update logic to include claimant as business
=> ROC-6412 Claimant mediation as business

src/main/app/claims/models/claim.ts, src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
https://tools.hmcts.net/jira/browse/ROC-6452
Update logic based on new claim-store rules
=> ROC-6452 Hide intention to proceed for older claims

src/main/app/claims/models/claim.ts, src/main/features/dashboard/views/macro/caseStatus.njk, src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk, src/test/features/dashboard/routes/dashboard/full-defence.ts
https://tools.hmcts.net/jira/browse/ROC-6453
=> ROC-6453 Mediation status for over £300

src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk, src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk, src/test/features/dashboard/routes/dashboard/part-admission.ts
https://tools.hmcts.net/jira/browse/ROC-6454
Update dashboards and fix route tests
=> ROC-6454 Part admit mediation dashboard

src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
=> update dashboard check to correct text

src/main/features/claimant-response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-6458
Update logic for showing mediation
=> ROC-6458 - Mediation check-and-send claimant response

src/main/app/paths.ts, src/main/routes/accessibility-statement.ts, src/main/views/accessibility-statement.njk, src/main/views/includes/support-links.njk
https://tools.hmcts.net/jira/browse/ROC-6521
Publish accessibility statement - OCMC Citizen
=> Added new acessibility statement page under footer lins

infrastructure/main.tf
update infrastructure to conform to new module
- [ x] No
=> update infrastructure module

src/main/features/claim/views/new-features-consent.njk, src/test/features/claim/routes/new-features-consent.ts
https://tools.hmcts.net/jira/browse/ROC-6567
Revert content and design of the 'New Features' page
=> Revert content and design of the 'New Features' page

src/main/features/claim/helpers/taskListBuilder.ts, src/main/features/claim/views/task-list.njk, src/main/features/claimant-response/views/task-list.njk, src/main/features/response/views/task-list.njk, src/main/public/stylesheets/components/_task-list.scss, src/test/features/response/helpers/taskListBuilder.ts
https://tools.hmcts.net/jira/browse/ROC-6058
- [x ] Unit tests added where applicable
- [ x] Route tests added for new pages
- [ x] New pages included in a11y tests
- [x ] Task list and task completeness checks updated
- [ x] Check and send page updated
- [ x] Routes, page content and page flows of new features are toggled 
- [x ] UI changes look good on mobile
- [x ] Required Google Analytics events are being sent 
- [ x] I have clicked through the running application to see if all changes I made actually work.
- [ x] No
=> ROC-6058: Update Task list content and style

src/main/features/response/routes/check-and-send.ts, src/main/features/response/routes/response-type.ts, src/main/features/response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-6601
=> ROC-6601 Mediation showing when it should not

src/main/features/claimant-response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-6609
Related to:
https://tools.hmcts.net/jira/browse/ROC-6458
Change YES to NO in check and send page to remove mediation text when the claimant settled for the paid offer.
=> ROC-6458 Changing check-and-send page logic 

src/main/app/drafts/draft-data/claimDraft.ts
https://tools.hmcts.net/jira/browse/ROC-4043
Create draft fails claim creation as mobile phone for defendant was added recently but the draft service was not adding that.
=> ROC-4043-Fix -Draft failure for the mobile phone of Defendant

src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk, src/test/features/dashboard/routes/dashboard/full-defence.ts
=> Fix typo in status

src/main/features/claimant-response/views/confirmation.njk
=> Confirmation page content fix

package.json, yarn.lock
=> Revert upgrades to fix builds

infrastructure/variables.tf
remove the use of *saat*
- [ x] No
=> update fees & pay default values

src/main/features/first-contact/views/claim-summary.njk, src/main/features/response/views/claim-details.njk
https://tools.hmcts.net/jira/browse/ROC-6904
Conditionally render the timeline on presence of the wrapping object
=> ROC-6904 Allow undefined timeline one the claim details page

src/integration-test/tests/citizen/claim/steps/claim.ts
=> Only delete drafts in non-prod

src/integration-test/tests/citizen/claim/enterDetails_test.ts, src/integration-test/tests/citizen/claim/steps/claim.ts
=> Update failing smoke test

Jenkinsfile_CNP
Just disable auto merging in jenkins build pipeline
- [x ] No
=> disable auto merging to demo

src/integration-test/tests/citizen/claim/enterDetails_test.ts, src/integration-test/tests/citizen/claim/steps/claim.ts
=> Delete drafts before running the tests

src/integration-test/tests/citizen/claim/enterDetails_test.ts, src/integration-test/tests/citizen/dashboard/dashboard_test.ts
=> Switch tests to nightly

src/integration-test/tests/citizen/claim/enterDetails_test.ts, src/integration-test/tests/citizen/dashboard/dashboard_test.ts
Run tests in pipeline with no retry to see error
=> Revert change to e2e tests

src/main/features/claim/routes/initiate-payment.ts
=> ROC-7142: Resume 404 frontend loop

src/main/features/claim/views/claimant-party-type-selection.njk, src/main/features/claim/views/defendant-party-type-selection.njk
https://tools.hmcts.net/jira/browse/ROC-6492
=> ROC-6492 Change label to 'A limited company'

src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk, src/test/features/dashboard/routes/claimStatus/full-defence.ts, src/test/features/dashboard/routes/claimStatus/part-admission.ts, src/test/features/dashboard/routes/claimStatus/states-paid.ts
https://tools.hmcts.net/jira/browse/ROC-7052
Content changes
=> ROC-7052: Failed mediation dashboard changes

src/main/public/waf.html
https://tools.hmcts.net/jira/browse/ROC-7027
Add a static page for WAF errors
=> ROC-7027 Static page for WAF errors

src/integration-test/data/test-data.ts
https://tools.hmcts.net/jira/browse/ROC-7216
remove hard coded offer date, to a date that will never be reached.
=> integration-test-fix-for-offer-date-in-test-data-to-never-expire

docker-compose.nightly-functional-tests.yml
This PR remove duplicate env variables from nightly configurations.
=> Remove duplicate env variables from nightly

src/main/features/claim/routes/initiate-payment.ts
=> Fix payment reference

infrastructure/ithc.tfvars, infrastructure/main.tf, infrastructure/variables.tf
fix app settings for staging slot
- [x ] No
=> fix app settings for staging slot

infrastructure/output.tf
=> fix output

infrastructure/main.tf
=> change cnp branch

infrastructure/main.tf, infrastructure/output.tf, infrastructure/variables.tf
=> revert app changes

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
upgrade nodeJs chart
- [ x] No
=> upgrade nodejs chart

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
Bump helm chart version as we have introduced breaking change by removing claim-store db references.
=> Bump helm chart version and dependency of claim-store

package.json, yarn.lock
=> Revert dependency upgrades

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml, charts/cmc-citizen-frontend/values.yaml
Reverts hmcts/cmc-citizen-frontend#2136
=> Revert "Cleaning up chart conditions"

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml, charts/cmc-citizen-frontend/values.yaml
=> add praveen changes 

src/integration-test/data/test-data.ts
[ROC-7473](url)
This PR adds postfix to functional test user, otherwise same user accumulate with too many claims and impacts the performance and causes failures.
=> ROC-7473: Add date as postfix to functional test user

src/integration-test/data/test-data.ts
ROC-7473
Update email pattern for test user
=> ROC-7473: Update email pattern for test user

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
upgrade to use latest claim-store chart
- [ x] No
=> upgrade claimstore chart

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/values.yaml
add  postcode-lookup-api-key
- [x ] No
=> add postcode lookup key

docker-compose.nightly-functional-tests.yml
https://tools.hmcts.net/jira/browse/ROC-7542
=> ROC-7542-remove duplicate smoke test users in config

package.json, yarn.lock
Seems to be failing on the ASE -.-
=> Remove app insights native metrics

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
fix postgres issues & update dependencies
- [x ] No
=> Fix postgres issues 

charts/cmc-citizen-frontend/values.preview.template.yaml, src/main/app/claims/models/Direction.ts
https://tools.hmcts.net/jira/browse/ROC-7567
Handle optional direction date
=> ROC-7567: Handle optional direction date

README.md, charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml, charts/cmc-citizen-frontend/values.yaml
to investigate issue found with cmc keyVault 
- [x ] No
=> [WIP] to investigate keyVault issue

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
upgrade postgresDB and bump chart version
- [ x] No
=> upgrade postgresDb and bump chart version

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
upgrade citizen-frontend to use latest claim-store chart
- [x ] No
=> upgrade claim-store

infrastructure/variables.tf
Enable web chat on all environment
=> Enable webchat on all environment

src/main/app/drafts/draft-data/claimDraft.ts
[ROC-7642](https://tools.hmcts.net/jira/browse/ROC-7642)
This PR fixes the draft discrepancies in testing support
=> ROC-7642: Fix draft discrepancies in testing support

infrastructure/variables.tf
=> Disable web chat

Jenkinsfile_nightly, docker-compose.nightly-functional-tests.yml
https://tools.hmcts.net/jira/browse/ROC-7594
Fix end-to-end tests failures
=> Updated nightly build failed configuration issue

charts/cmc-citizen-frontend/Chart.yaml
=> bump frontend chart version

infrastructure/aat.tfvars
https://tools.hmcts.net/jira/browse/ROC-7697
Enable web chat in aat
=> Enable web chat in aat

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
raise a new PR to verify if issues occurs here again
- [x ] No
=> fixing pr issues

src/main/public/stylesheets/application.scss, src/main/public/stylesheets/components/_banner.scss, src/main/public/stylesheets/components/_colours.scss, src/main/views/govukTemplate.njk, src/main/views/includes/banner.njk, src/main/views/layout.njk
https://tools.hmcts.net/jira/browse/ROC-7769
Banner to warn people CCBC is down
=> ROC-7769-Banner to warn people CCBC is down

src/main/views/layout.njk
https://tools.hmcts.net/jira/browse/ROC-7813
CCBC is back open, so remove the warning banner previously implemented in ROC-7769
=> ROC-7813 Take down downtime banner

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml
upgrade to latest nodejs-chart version
- [x ] No
=> upgrade nodejs chart and bump version

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-8270
=> RDM-8270 Upgrade ccd definition version to 1.5.15.3

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
update to use nodejs-chart version 1.10.1
- [ x] No
=> update to use latest nodejs chart

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-8293
=> RDM-8293 Upgrade ccd definition version to 1.5.16

src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedClaimant.njk, src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedDefendant.njk, src/test/features/dashboard/routes/claimStatus/ccj.ts, src/test/features/dashboard/routes/claimStatus/full-admission.ts, src/test/features/dashboard/routes/claimStatus/part-admission.ts
https://tools.hmcts.net/jira/browse/ROC-7872
Update-Dashboard-About-Offline-Journey-When-repayment-plan-requested
=> ROC-7872-Update-Dashboard-About-Offline-Journey-When-repayment-plan-requested

charts/cmc-citizen-frontend/values.aat.template.yaml
This PR fixes the broken pipelines.
=>  ROC-7890: Fix pipelines

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-8494
=> RDM-8494 Upgrade ccd definition version to 1.5.17

gulpfile.js
https://tools.hmcts.net/jira/browse/ROC-7287
=> Fixed gulp task issue

Jenkinsfile_nightly, Jenkinsfile_parameterized
remove future toggle key from jenkins file
- [ x] No
=> remove ft key-vault key

src/main/app/claims/models/claim.ts
https://tools.hmcts.net/jira/browse/ROC-8007
=> Applying Filter for all the documentTypes coming from claim-store

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-8562
=> RDM-8562 Upgrade ccd definition version to 1.5.18

src/main/common/clients/launchDarklyClient.ts, src/main/features/claim/helpers/featuresBuilder.ts, src/test/features/claim/helpers/featuresBuilder.ts, src/test/features/claim/routes/pay.ts
https://tools.hmcts.net/jira/browse/ROC-7994
Remove responsibility for verifying consent given for new features from LaunchDarkly and give it to the frontend.
=> ROC-7994 Refactor feature builder

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/requirements.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
upgrade ccd-chart and idam-pr and release 1.6.1 definition
- [x ] No
=> bump chart version

src/main/features/claim/helpers/featuresBuilder.ts, src/test/features/claim/helpers/featuresBuilder.ts
https://tools.hmcts.net/jira/browse/ROC-8056
Amend the features builder component to allow more complex logic to determine feature eligibility, and update the Judge pilot's criteria to include the claim amount being greater than the LA pilot threshold
=> ROC-8056 Cannot have LA and Judge pilot features at the same time

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/values.yaml
remove ff4j from chart default values
- [x ] No
=> remove ff4j from chart default values

config/custom-environment-variables.json, config/default.json, config/development.json, config/dockertests.json, config/mocha.json, src/main/app/drafts/models/draftClaim.ts, src/main/app/utils/featureToggles.ts, src/main/common/clients/launchDarklyClient.ts, src/main/features/claim/helpers/featuresBuilder.ts, src/main/features/eligibility/eligibilityPage.ts, src/main/features/eligibility/model/eligibility.ts, src/main/features/eligibility/routes/claim-is-for-tenancy-deposit.ts, src/main/features/eligibility/routes/claim-type.ts, src/main/features/eligibility/routes/claim-value.ts, src/main/features/eligibility/routes/claimant-address.ts, src/main/features/eligibility/routes/defendant-address.ts, src/main/features/eligibility/routes/defendant-age.ts, src/main/features/eligibility/routes/government-department.ts, src/main/features/eligibility/routes/help-with-fees-reference.ts, src/main/features/eligibility/routes/help-with-fees.ts, src/main/features/eligibility/routes/over-18.ts, src/main/features/eligibility/routes/single-defendant.ts, src/main/routes/receiver.ts, src/test/app/utils/featureToggles.ts, src/test/features/claim/helpers/featuresBuilder.ts, src/test/features/claim/routes/pay.ts
Story: https://tools.hmcts.net/jira/browse/ROC-7959
Sub-task: https://tools.hmcts.net/jira/browse/ROC-8098
Use launchdarkly to decide if help with fees is enabled instead of the environment variable.
See: https://github.com/hmcts/cmc-citizen-frontend/pull/2338
=> ROC-7959, ROC-8098 LaunchDarkly toggle

src/test/app/claims/models/claim.ts
Fix for the nit test failures
Fix for the nit test failures
=> fix for the unit test failure

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-9032
1. ROC-8159-Null pointer Exception on Change Contact Details Page
2. ROC- ROC-8161 OCON toggle
- [ X] No
=> ROC-9032 bumping ccd version in values.preview.template.yaml

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-9019
https://tools.hmcts.net/jira/browse/ROC-8083
CCD config changes for pcq integration
=> RDM-9019 bumping ccd version in values.preview.template.yaml

charts/cmc-citizen-frontend/Chart.yaml, src/main/views/privacy-policy.njk
https://tools.hmcts.net/jira/browse/ROC-6540
Content change in the money claims privacy policy page
=> ROC-6540-Update-Money-claim-Privacy-Policy

src/main/app/forms/validation/formValidator.ts, src/main/public/js/postcode-lookup.js, src/test/app/forms/validation/formValidator.ts
https://tools.hmcts.net/jira/browse/ROC-8276
Postcode is trimmed and replaced with space for any non breaking space in between
=> ROC-8276 Postcode validation

charts/cmc-citizen-frontend/values.preview.template.yaml, src/main/app/forms/models/organisationDetails.ts, src/main/features/dashboard/views/macro/claimStatus/claimTransferred.njk, src/test/features/claim/routes/claimant-organisation-details.ts, src/test/features/claim/routes/defendant-organisation-details.ts, src/test/http-mocks/draft-store.ts
https://tools.hmcts.net/jira/browse/ROC-8275
Added the validation on the defendant [another type of organisation] contact person character length. It should be less than 30.
=> ROC-8275-Validation-Contact-person-character-length

charts/cmc-citizen-frontend/values.preview.template.yaml
=> CCD Def Version Bump

charts/cmc-citizen-frontend/Chart.yaml, charts/cmc-citizen-frontend/values.preview.template.yaml
=> Rdm 9523 bump ccd version

gulpfile.js, src/main/public/stylesheets/govuk-frontend/task-list.scss
Reverts hmcts/cmc-citizen-frontend#2511
=> Revert "Bug/roc 8224 task list"

charts/cmc-citizen-frontend/Chart.yaml
=> Renovate/cmc claim store 4.x

charts/cmc-citizen-frontend/Chart.yaml
=> Renovate/postgresql 9.x

src/main/features/claimant-response/views/check-and-send.njk
https://tools.hmcts.net/jira/browse/ROC-8431
> Free telephone mediation content style issue
=> [Bug Fix] Claimant-Response : Check and send page issue 

infrastructure/main.tf
Reverts hmcts/cmc-citizen-frontend#2559
=> Revert "Update terraform"

audit.json
=> Added 'SQL Injection - Oracle - Time Based' to the exception list

docker-compose.functional-tests.yml, docker-compose.nightly-functional-tests.yml, docker-compose.smoke-tests.yml
=> Remove proxyout config

README.md
> update all signposts in OCMC Pages with new opening hours for CTSC contact center
> https://tools.hmcts.net/jira/browse/ROC-8534
> This is dummy PR to fix the cluster issues. The previous PR-2596 is not correctly deployed in all the 6 PRD pods, due to this for subsequent request the html contents (New work hours) are deferring.
=> Update all signposts in OCMC Pages with new opening hours for CTSC contact center

src/main/app/claims/claimStoreClient.ts
=> add explicit timeout param

src/main/views/contact-us.njk, src/main/views/macro/support.njk
https://tools.hmcts.net/jira/browse/ROC-8574
> Remove the static text "We‘re experiencing intermittent problems with our phone line. Email us if you can't get through." from contact-us page.
> Update the email ID to contactocmc@justice.gov.uk
=> Removing the static downtime (Intermediate issue) content from the contact-us page

config/default.json, default.conf.js
=> incease default timeout

package.json, yarn.lock
=> Dependabot/npm and yarn/types/lodash 4.14.165

package.json, yarn.lock
=> Dependabot/npm and yarn/sinon 9.2.1

src/main/app.ts, src/main/server.ts
=> temporary logging for cpu usgae issue

README.md, src/integration-test/tests/citizen/endToEnd/endToend_test.ts, src/integration-test/tests/citizen/govukAccessRoutes/returnToClaim_test.ts, src/integration-test/tests/citizen/offers/offers_test.ts
=> Roc 8625 dummy branch

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-10905
Bump version to 1.8.9
=> Bump version to 1.8.9

charts/cmc-citizen-frontend/values.preview.template.yaml
Bump version 1.9.3
Bump version to 1.93
=> Bump CCD Version as part of HWF deployment

Jenkinsfile_nightly
=> update nightly build timing

default.conf.js, src/integration-test/tests/citizen/claim/enterDetails_test.ts, src/integration-test/tests/citizen/claim/helpWithFees_test.ts, src/integration-test/tests/citizen/offers/offers_test.ts
https://tools.hmcts.net/jira/browse/TA-457
1) Test Code Improvements
2) Added Before()
3) Added additional threads to reduce the functional tests execution time (13 mins)
- [x ] No
=> Ta 457 claimant help with fee e2 e

src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts, types/steps.d.ts
https://tools.hmcts.net/jira/browse/TA-454
1. Test Code Improvements
2. Full Admission--> Interlocutory Judgement  E2E
- [ x] No
=> TA-454-Interlocutory-JudgementE2E

charts/cmc-citizen-frontend/values.preview.template.yaml, package.json, saucelabs.conf.js, src/integration-test/tests/citizen/endToEnd/endToend_test.ts
https://tools.hmcts.net/jira/browse/TA-369
Run `@crossbrowser` tagged e2e test "I can as an Individual make a claim against an Individual Without a defendant email address and are able to pay on the Gov Pay page" as the nightly crossbrowser suite.
=> TA-369: Run crossbrowser tests on chrome

Jenkinsfile_nightly, bin/run-crossbrowser-tests.sh, charts/cmc-citizen-frontend/values.preview.template.yaml, package.json, src/integration-test/bootstrap/bootstrap.ts, src/integration-test/bootstrap/teardown.ts, src/integration-test/helpers/pcqHelper.js
https://tools.hmcts.net/jira/browse/TA-370
Run @crossbrowser tagged e2e test in both Firefox and Chrome via a new ./bin/run-crossbrowser-tests.sh runner. This runs the browser groups one after the other, and returns an exit code based on all the browsers - i.e. if one browser fails the next browser is still run, but the overall build job is marked failed.
Includes a small refactor of bootstrapAll e2e test setup to await all criteria before continuing.
=> TA-370: Run crossbrowser tests on Firefox

default.conf.js, src/integration-test/tests/citizen/offers/offers_test.ts
https://tools.hmcts.net/jira/browse/TA-489
1.  Test Code Improvements
2. Offers Additional Tests
3. Webdriver Config Update
- [ x] No
=> TA-489-Offers Additional Tests

src/integration-test/tests/citizen/offers/offers_test.ts
https://tools.hmcts.net/jira/browse/TA-508
Limit cross browser tests to single end to end journey on cmc
=> TA-508: Limit cross browser tests to single end to end journey on cmc

src/integration-test/tests/citizen/ccj/ccj_test.ts, src/integration-test/tests/citizen/ccj/companyCCJ_test.ts, src/integration-test/tests/citizen/ccj/pages/ccj-check-and-send.ts, src/integration-test/tests/citizen/ccj/pages/defendant-paid-any-money.ts, src/integration-test/tests/citizen/ccj/pages/paid-amount-summary.ts, src/integration-test/tests/citizen/ccj/soleTraderCCJ_test.ts, src/integration-test/tests/citizen/ccj/steps/ccj.ts
https://tools.hmcts.net/jira/browse/TA-474
1. Default CCJ E2E
2. Test Code Improvements
3. Removed Crossbrowser tag
- [ x] No
=> Ta 474 Default CCJ Additional Tests

src/integration-test/tests/citizen/claimantResponse/part_admission_defendant_is_business_test.ts, src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts, src/integration-test/tests/citizen/endToEnd/fullAdmission_test.ts, src/integration-test/tests/citizen/endToEnd/partAdmission_test.ts
https://tools.hmcts.net/jira/browse/TA-514
1. Part Admission E2E Test Code Refactoring
2. Part admit when defendant is business Code refactoring
3. Company Rejected the part admit offer
- [ x] No
=> TA 514 Part Admission Business E2E (New)

default.conf.js, src/integration-test/tests/citizen/ccj/ccj_test.ts, src/integration-test/tests/citizen/ccj/claimantCCJ_test.ts, src/integration-test/tests/citizen/ccj/companyCCJ_test.ts, src/integration-test/tests/citizen/ccj/organisation_test.ts, src/integration-test/tests/citizen/claim/helpWithFees_test.ts, src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts, src/integration-test/tests/citizen/endToEnd/settleClaim_test.ts
https://tools.hmcts.net/jira/browse/TA-532
1. Settle Claim Additional Scenarios
2. Test Code Improvements
- [ x] No
=> TA- 532-Settle Claim Scenarios(New)

package.json, yarn.lock
=> fixed cves

src/integration-test/tests/citizen/defence/defence_handoff_test.ts, src/integration-test/tests/citizen/endToEnd/defence_test.ts, src/integration-test/tests/citizen/endToEnd/fullDefence_test.ts
https://tools.hmcts.net/jira/browse/TA-518
https://tools.hmcts.net/jira/browse/TA-505
-
-  Case Stayed E2E
- . Full Defence E2E Scenarios
- . Defence Handoff tests code refactoring
-  Test Code Improvements
- [ x] No
=> TA-517-Full Defence E2E & Claimant Stop The Claim E2E

README.md
=> sonarcloud quality gate issue fix in master branch

README.md, package.json, src/test/app/claims/models/claim.ts, src/test/http-mocks/claim-store.ts
NA
Sonarqube quality gate failure in master. 
> Added additional test case.
=> Sonarqube quality gate failure added additional test case.  

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-8979
=> fixed cves from rpe dashboard

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-11642
Bump version
=> bump the version for ccd release

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-11642
CCD release
=> bump version

src/main/features/ccj/routes/check-and-send.ts, src/main/features/ccj/routes/paid-amount-summary.ts, src/test/app/claims/models/claim.ts, src/test/features/ccj/routes/check-and-send.ts, src/test/features/ccj/routes/paid-amount-summary.ts, src/test/http-mocks/claim-store.ts
https://tools.hmcts.net/jira/browse/ROC-8946
Pay by set date-CCJ issue
- [x ] Route tests added for new pages
- [ x] No
=> ROC-8946: Issue CCJ request fix when defendant selects pay by set date

charts/cmc-citizen-frontend/values.preview.template.yaml
=> Rdm 12015 bumping ccd ver to 1.10.2

README.md, src/main/features/directions-questionnaire/routes/hearing-location.ts
=> Fix for Incorrect court used in defendant response

src/main/modules/helmet/modules/contentSecurityPolicy.ts
NA
> Fixing invalid URL : http://www.moneyclaims.service.gov.uk/report-violation. Which has been introduced as part of CSP **reportUri**
> Tested in demo (pre-implementation test) vs this PR deployment (post-implementation test). The changes in this PR is not breaking anything.
> 
> ![image](https://user-images.githubusercontent.com/41957682/116282839-2a781800-a783-11eb-9e13-f4df5d3f5d6b.png)
> ![image](https://user-images.githubusercontent.com/41957682/116283057-61e6c480-a783-11eb-94ac-da5af742d74d.png)
=> Fixing the production page not found issue

package.json, yarn.lock
=> Yarn audit fix

charts/cmc-citizen-frontend/values.preview.template.yaml
=> RDM-12394-bumping-ccd-ver-to-1.10.5

src/main/resources/meansAllowance.json
=> Update to statement of means allowance

package.json, src/integration-test/tests/citizen/endToEnd/defence_test.ts, src/main/modules/nunjucks/index.ts, src/main/public/waf.html, src/main/views/govukTemplate.njk, src/main/views/layout.njk, yarn.lock
https://tools.hmcts.net/jira/browse/ROC-9204
=> ROC-9204-gov.uk-cookie-banner-removed

src/main/common/components/payment-intention/payment-date.njk, src/main/common/components/payment-intention/payment-plan.njk, src/main/features/breathing-space/views/respite-end.njk, src/main/features/breathing-space/views/respite-lifted.njk, src/main/features/breathing-space/views/respite-start.njk, src/main/features/ccj/views/date-of-birth.njk, src/main/features/ccj/views/pay-by-set-date.njk, src/main/features/ccj/views/repayment-plan.njk, src/main/features/claim/views/claimant-dob.njk, src/main/features/claim/views/interest-start-date.njk, src/main/features/claimant-response/views/payment-plan.njk, src/main/features/directions-questionnaire/views/expert-reports.njk, src/main/features/directions-questionnaire/views/hearing-dates.njk, src/main/features/offer/views/your-offer.njk, src/main/features/paid-in-full/views/date-paid.njk, src/main/features/response/views/evidence.njk, src/main/features/response/views/full-rejection/how-much-have-you-paid.njk, src/main/features/response/views/how-much-paid.njk, src/main/features/response/views/partial-admission/how-much-have-you-paid.njk, src/main/features/response/views/when-did-you-pay.njk, src/main/features/response/views/your-dob.njk, src/main/features/testing-support/views/update-response-deadline.njk, src/main/views/macro/date.njk
https://tools.hmcts.net/jira/browse/ROC-8386
Accessibility: unnamed evidence table in defendant response
=> change for DAC

package.json, src/main/app/postcode-lookup/clientFactory.ts, src/main/app/postcode-lookup/postcodeToCountryClient.ts, src/test/app/forms/validation/validators/isCountrySupported.ts, src/test/app/postcode-lookup/postcodeToCountryClient.ts, src/test/data/entity/mockCountryLookupResponse.ts, src/test/data/entity/mockPostcodeLookupResponse.ts, src/test/routes/postcode-lookup.ts, yarn.lock
=> Post code lookup fix

src/integration-test/tests/citizen/claimantResponse/part_admission_defendant_is_business_test.ts
https://tools.hmcts.net/jira/browse/ROC-9192
Failed nightly test removed temporarily
=> fix nightly

Jenkinsfile_CNP
=> environment sync up

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CFTS-729
=> bumb ccd version

charts/cmc-citizen-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/ROC-9230
https://tools.hmcts.net/jira/browse/ROC-9496
=> bump ccd version

charts/cmc-citizen-frontend/values.preview.template.yaml
=> bump ccd definition importer to 1.10.20

src/main/features/claim/helpers/featuresBuilder.ts
This reverts commit 8a8e8e1e0ebdac865f0286453b0b02594bf19564.
Revert merge to master story ROC 9208
=> Revert "Roc 9208 update LADO claims threshold (#3294)"

charts/cmc-citizen-frontend/values.preview.template.yaml
=> Update definition importer to the latest version

Jenkinsfile_nightly
=> Disable security scan until reform fix it

.github/CODEOWNERS.md
https://tools.hmcts.net/jira/browse/CIV-1186
Added default reviewers
=> CIV-1186 : added default reviewers

charts/cmc-citizen-frontend/values.preview.template.yaml, src/main/views/macro/support.njk
https://github.com/hmcts/cmc-citizen-frontend/tree/CIV-1795
=> New pr for civ 1795

src/main/routes/monthly-income-expense-calculation.ts
https://tools.hmcts.net/jira/browse/CIV-1924
Resolved the following security issues:
- Exception text reinterpreted as HTML 
- Information exposure through a stack trace
=> CIV-1924 : resolved security vulnerabilities

Dockerfile, integration-tests.Dockerfile, package.json, yarn.lock
PR raised to upgrade puppeteer and fix master:
=> puppeteer upgrade

src/main/features/claim/routes/finish-payment.ts
https://tools.hmcts.net/jira/browse/CIV-3520
=> add logs for finish payment

charts/cmc-citizen-frontend/Chart.yaml
=> Update chart.yaml for node.js to 2.4.5

bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-3513)
Add new ccd role for retain and dispose
- [ x] No
=> Add new ccd role for retain and dispose

charts/cmc-citizen-frontend/values.preview.template.yaml
=> update preview to use claim-store master

src/test/a11y/a11y.ts
=> fix master pipeline

charts/cmc-citizen-frontend/Chart.yaml
=> bump charts version

src/main/modules/nunjucks/index.ts, src/main/views/govukTemplate.njk
=> CIV-446: Add nonce to inline script

src/main/modules/helmet/modules/contentSecurityPolicy.ts, src/main/modules/nunjucks/index.ts
=> CIV-446: Update content security policy

src/main/views/macro/support.njk
https://tools.hmcts.net/jira/browse/CIV-6379
Update contact us page for Christmas holidays notification
=> CIV-6379: Christmas Holidays Notification

package.json, yarn.lock
=> udpate packages

charts/cmc-citizen-frontend/Chart.yaml
Bump CCD chart verion to 8.0.23
=> bump ccd charts version

charts/cmc-citizen-frontend/Chart.yaml
=> CIV-9999: Fix master pipeline

charts/cmc-citizen-frontend/Chart.yaml, src/main/modules/helmet/modules/contentSecurityPolicy.ts
https://tools.hmcts.net/jira/browse/CIV-446
enable google tagging on cmc frontend
- [x ] No
=> update content security policy to allow google tagging

src/integration-test/bootstrap/bootstrap.ts, src/integration-test/bootstrap/teardown.ts, src/integration-test/helpers/clients/idamClient.ts
=> Fix master pipelines

src/integration-test/bootstrap/bootstrap.ts, src/integration-test/bootstrap/teardown.ts, src/integration-test/helpers/clients/idamClient.ts
=> Add log statement

charts/cmc-citizen-frontend/values.preview.template.yaml, src/integration-test/bootstrap/bootstrap.ts
=> Clean up logs

src/main/modules/helmet/modules/contentSecurityPolicy.ts
=> CIV-446 update csp

.eslintrc.js, Dockerfile, README.md, integration-tests.Dockerfile, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/CIV-8456
=> CIV 8456 upgrade to 18

Jenkinsfile_CNP
=> CIV-0000 fix master

src/main/views/accessibility-statement.njk
https://tools.hmcts.net/jira/browse/CIV-11707
=> CIV-11707 update OCMC domain

Jenkinsfile_nightly, security.sh
=> DTSCCI-180: cmc-citizen-frontend nightly is failing on security scan

.github/workflows/push.yml, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/DTSCCI-60
Reduce CVEs
=> DTSCCI-60 - Reduce CVEs

package.json, src/main/server.ts, yarn.lock
Logs dont appear in appinsights and it seems to be an issue due to order of imports where appinsights needs to be imported and setup before logger is used.
=> Dtscci 195

src/main/routes/receiver.ts
https://tools.hmcts.net/jira/browse/DTSCCI-493
=> DTSCCI-493: Add logging

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/DTSCCI-876
=> DTSCCI-876 - Update regexp
